

- name: ensure  directory exists
  ansible.builtin.file:
    path: "{{ hive_path }}"
    state: directory


- debug:
    msg: "Downloading hive from {{ hive_download }}"


- name: Unzip hive
  unarchive:
    src: "{{ hive_download }}"
    dest: "{{ hive_path }}"
    remote_src: yes
    creates: "{{ hive_home }}"
    group: "{{ hive_user.group }}"
    owner: "root"


- name: "Link {{ hive_home }} to {{ current_hive_home }}"
  ansible.builtin.file:
    src: "{{ hive_home }}"
    dest: "{{ current_hive_home }}"
    state: link


- name: Upload hive config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ hive_config_path }}/"
    mode: 0644
    owner: "root"
    group: "{{ hive_user.group }}"
  with_fileglob:
    - "templates/hive_conf/*"


- name: remove {{ hive_home }}/conf
  ansible.builtin.file:
    path: "{{ hive_home }}/conf"
    state: absent
- name: symlink {{ hive_home }}/conf to {{ hive_config_path }}
  ansible.builtin.file:
    src: "{{ hive_config_path }}"
    dest:  "{{ hive_home }}/conf"
    owner: root
    group: "{{ hive_user.group }}"
    state: link
    force: true


- name: Upload Hive profile files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/profile.d/"
    mode: 0644
    owner: "root"
    group: "{{ hive_user.group }}"
  with_fileglob:
    - "templates/profile.d/*"

