

- name: ensure  directory exists
  file:
    path: "{{ hive_path }}"
    state: directory


- debug:
    msg: "Downloading hive from {{hive_download}}"


- name: Unzip hive
  unarchive:
    src: "{{ hive_download }}"
    dest: "{{ hive_path }}"
    remote_src: yes
    creates: "{{ hive_home }}"
    group: "{{ hive_group }}"
    owner: "root"


- name: "Link {{hive_home}} to {{current_hive_home}}"
  file:
    src: "{{hive_home}}"
    dest: "{{current_hive_home}}"
    state: link


- name: Upload hive config files
  template:
    src: "{{ item }}"
    dest: "{{ hive_config_path }}/"
    mode: 0644
    owner: "root"
    group: "{{ hive_group }}"
  with_fileglob:
    - "templates/hive_conf/*"


- name: remove {{ hive_home }}/conf
  file:
    path: "{{ hive_home }}/conf"
    state: absent
- name: symlink {{ hive_home }}/conf to {{ hive_config_path }}
  file:
    src: "{{ hive_config_path }}"
    dest:  "{{ hive_home }}/conf"
    owner: root
    group: "{{ hive_group }}"
    state: link
    force: true


- name: Upload Hive profile files
  template:
    src: "{{ item }}"
    dest: "/etc/profile.d/"
    mode: 0644
    owner: "root"
    group: "{{ hive_group }}"
  with_fileglob:
    - "templates/profile.d/*"

