---
- name: ensure zookeeper directory exists
  file:
    path: "{{ zookeeper_path }}"
    state: directory

- name: Unzip Zookeeper
  unarchive:
    src: "{{ zookeeper_download }}"
    dest: "{{ zookeeper_path }}"
    remote_src: yes
    creates: "{{ zookeeper_path }}/zookeeper-{{ zookeeper_version }}"
    group: "{{ zookeeper_group }}"
    owner: "root"


- name: Create Zookeeper Paths
  file:
    path: "{{ item }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ zookeeper_create_path }}"

- name: Copy Zookeeper config files
  template:
    src: "{{ item }}"
    dest: "{{ zookeeper_config_path }}/"
    mode: 0644
    owner: "root"
    group: "{{ zookeeper_group }}"
  with_fileglob:
    - "templates/conf/*"


- name: Copy Hadoop Zookeeper systemd services
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: 0644
    owner: "root"
    group: "root"
  with_fileglob:
    - "templates/systemd/*"

- name: zookeeper_id
  template: src=myid dest={{zookeeper_data_dir}}/myid mode=0644 owner="root" group="root"
  when: zookeeper_server

- name: Start zookeeper server
  systemd:
    state: started
    daemon_reload: yes
    name: zookeeper
  when: zookeeper_server and start
