---
- name: ensure zookeeper directory exists
  ansible.builtin.file:
    path: "{{ zookeeper_path }}"
    state: directory


- ansible.builtin.debug:
    msg: "Downloading Zookeeper from {{ zookeeper_download }}"

- name: Unzip Zookeeper
  ansible.builtin.unarchive:
    src: "{{ zookeeper_download }}"
    dest: "{{ zookeeper_path }}"
    remote_src: yes
    creates: "{{ zookeeper_home }}"
    group: "{{ zookeeper_user.group }}"
    owner: "root"


- name: "Link {{ zookeeper_home }} to {{ current_zookeeper_home }}"
  ansible.builtin.file:
    src: "{{ zookeeper_home }}"
    dest: "{{ current_zookeeper_home }}"
    state: link


- name: Create Zookeeper Paths
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ zookeeper_user.name }}"
    group: "{{ zookeeper_user.group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ zookeeper_create_path }}"

- name: install log4jSyslogWriter64k in classpath
  include_tasks: installLog4jSyslogAppender.yml
  vars:
    dest: "{{ current_zookeeper_home }}/lib/"
    owner:
      name: root
      group: "{{ zookeeper_user.group }}"

- name: Upload Zookeeper config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ zookeeper_config_path }}/"
    mode: 0644
    owner: "root"
    group: "{{ zookeeper_user.group }}"
  with_fileglob:
    - "templates/conf/*"


- name: Upload Hadoop Zookeeper systemd services
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: 0644
    owner: "root"
    group: "root"
  with_fileglob:
    - "templates/systemd/*"

