---
- name: ensure zookeeper directory exists
  file:
    path: "{{ zookeeper_path }}"
    state: directory


- debug:
    msg: "Downloading Zookeeper from {{zookeeper_download}}"

- name: Unzip Zookeeper
  unarchive:
    src: "{{ zookeeper_download }}"
    dest: "{{ zookeeper_path }}"
    remote_src: yes
    creates: "{{zookeeper_home}}"
    group: "{{ zookeeper_user.group }}"
    owner: "root"


- name: "Link {{zookeeper_home}} to {{current_zookeeper_home}}"
  file:
    src: "{{zookeeper_home}}"
    dest: "{{current_zookeeper_home}}"
    state: link


- name: Create Zookeeper Paths
  file:
    path: "{{ item }}"
    owner: "{{ zookeeper_user.name }}"
    group: "{{ zookeeper_user.group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ zookeeper_create_path }}"

- name: Upload Zookeeper config files
  template:
    src: "{{ item }}"
    dest: "{{ zookeeper_config_path }}/"
    mode: 0644
    owner: "root"
    group: "{{ zookeeper_user.group }}"
  with_fileglob:
    - "templates/conf/*"


- name: Upload Hadoop Zookeeper systemd services
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: 0644
    owner: "root"
    group: "root"
  with_fileglob:
    - "templates/systemd/*"

