

- name: "Check for single mapreduce_history_server"
  assert:
    that: "groups['hostgroup_mapreduce_history_servers'] | length == 1"


- name: "Check for 0-1 spark_history_server"
  assert:
    that: "groups['hostgroup_spark_history_servers'] | length <= 1"


# HDFS
- name: HDFS
  block:
    - name: "Check for 0-1 backup namenode"
      assert:
        that: "groups['hostgroup_hdfs_backupnodes'] |length  <= 1"

- name: HDFS non-HA
  when: "not hdfs_high_availability"
  block:
    - name: "Check for Single namenode when NOT using HDFS High Availability"
      assert:
        that: "groups['hostgroup_hdfs_namenodes'] |length  == 1"

    - name: "Check for 0-1 secondary namenode when NOT using HDFS High Availability"
      assert:
        that: "groups['hostgroup_hdfs_secondary_namenodes'] |length <= 1"

    - name: "Check for 0 journal nodes when NOT using HDFS High Availability"
      assert:
        that: "groups['hostgroup_hdfs_journalnodes'] | length == 0"



- name: HDFS HA
  when: "hdfs_high_availability"
  block:
    - name: "Check for 3+ journal nodes when using HDFS High Availability"
      assert:
        that: "groups['hostgroup_hdfs_journalnodes'] | length >= 3"

    - name: "Check for 2+ namenodes nodes when using HDFS High Availability"
      assert:
        that: "groups['hostgroup_hdfs_namenodes'] | length >= 2"

    - name: "Check for 0 secondary namenode when using HDFS High Availability"
      assert:
        that: "groups['hostgroup_hdfs_secondary_namenodes'] |length == 0"

    - name: "Check for 3+ zookeeper servers when using High Availability"
      assert:
        that: "groups['hostgroup_zookeeper_servers'] | length >= 3"




- name: YARN
  block:
    - name: "Check for single yarn_timeline_server"
      assert:
        that: "groups['hostgroup_yarn_timeline_servers'] | length == 1"


- name: YARN non-HA
  when: "not yarn_high_availability"
  block:
    - name: "Check for single Yarn Resourcemager when NOT using YARN High Availability"
      assert:
        that: "groups['hostgroup_yarn_resource_managers'] | length == 1"

    - name: "Check for 1+ zookeeper servers when NOT using High Availability"
      assert:
        that: "groups['hostgroup_zookeeper_servers'] | length >= 1"


- name: YARN HA
  when: "yarn_high_availability"
  block:
    - name: "Check for 2+ Yarn Resourcemager when using YARN High Availability"
      assert:
        that: "groups['hostgroup_yarn_resource_managers'] | length >= 2"

    - name: "Check for 3+ zookeeper servers when using YARN High Availability"
      assert:
        that: "groups['hostgroup_zookeeper_servers'] | length >= 3"


