---
# https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipaclient/README.md#base-variables

#TODO iprange for nfs export
default_ipa_server: "{{ groups['ipaserver'] | first }}"

default_ipa_admin_user: admin
default_ipa_admin_group: admins

default_ipaserver_autohome_dir: /sto-data/home
default_ipaserver_syshome_dir: /sto-data/syshome

default_ipaclient_autohome_dir: /autohome
default_ipaclient_syshome_dir: /syshome
#Nessesary to set up the automount
default_ipaautomount_location: "default"

#Users and groups
default_hadoop_group: "hadoop"
default_uid_hadoopGroup: 11000

default_users_group: "yakusers"
default_uid_usersGroup: 20000

default_systemservices_group: "systemservices"
default_uid_systemserviceGroup: 15000

default_subadmins_group: "subadmins"
default_uid_subadminsGroup: 12000


default_hdfs_user: "hdfs"
default_hdfs_group: "hdfs"
default_hdfs_uid: 11200
default_hdfs_gid: 11200

default_yarn_user: "yarn"
default_yarn_group: "{{hadoop_group}}"
default_yarn_uid: "{{uid_hadoopGroup|int+2}}"
default_yarn_gid: "{{uid_hadoopGroup}}"

default_mapreduce_user: "mapred"
default_mapreduce_group: "{{hadoop_group}}"
default_mapreduce_uid: "{{uid_hadoopGroup|int+1}}"
default_mapreduce_gid: "{{uid_hadoopGroup}}"

default_zookeeper_user: "zookeeper"
default_zookeeper_group: "{{hadoop_group}}"
default_zookeeper_uid: "{{uid_hadoopGroup|int+3}}"
default_zookeeper_gid: "{{uid_hadoopGroup}}"

default_spark_user: "spark"
default_spark_group: "{{hadoop_group}}"
default_spark_uid: "{{uid_hadoopGroup|int+4}}"
default_spark_gid: "{{uid_hadoopGroup}}"


default_system_users:
  - user: "{{hdfs_user}}"
    group: "{{hdfs_group}}"
    uid: "{{hdfs_uid}}"
    gid: "{{hdfs_gid}}"

  - user: "{{yarn_user}}"
    group: "{{yarn_group}}"
    uid: "{{yarn_uid}}"
    gid: "{{yarn_gid}}"

  - user: "{{mapreduce_user}}"
    group: "{{mapreduce_group}}"
    uid: "{{mapreduce_uid}}"
    gid: "{{mapreduce_gid}}"

  - user: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
    uid: "{{zookeeper_uid}}"
    gid: "{{zookeeper_gid}}"

  - user: "{{spark_user}}"
    group: "{{spark_group}}"
    uid: "{{spark_uid}}"
    gid: "{{spark_gid}}"
#
#  - user: "{{ipa_admin_user}}"
#    group: "{{ipa_admin_group}}"

standard_user_groups:
  - name: "{{ hadoop_group }}"
    gid: "{{ uid_hadoopGroup }}"
    description: Hadoop System Services
  - name: "{{ systemservices_group }}"
    gid: "{{ uid_systemserviceGroup }}"
    description: Standard user accounts, for non-hadoop services
  - name: "{{ subadmins_group }}"
    gid: "{{ uid_subadminsGroup }}"
    description: For daily administration of users and hosts
  - name: "{{ users_group }}"
    gid: "{{ uid_usersGroup }}"
    description: Standard user accounts, for unprivileged users.
  - name: "{{ hdfs_group }}"
    gid: "{{ hdfs_gid }}"
    description: HDFS group

default_user_groups: "{{standard_user_groups}}"