---

standard_user_groups:
  - name: "{{ hadoop_group }}"
    gid: "{{ uid_hadoopGroup }}"
    description: Hadoop System Services
  - name: "{{ systemservices_group }}"
    gid: "{{ uid_systemserviceGroup }}"
    description: Standard user accounts, for non-hadoop services
  - name: "{{ subadmins_group }}"
    gid: "{{ uid_subadminsGroup }}"
    description: For daily administration of users and hosts
  - name: "{{ users_group }}"
    gid: "{{ uid_usersGroup }}"
    description: Standard user accounts, for unprivileged users.
  - name: "{{ hdfs_group }}"
    gid: "{{ hdfs_gid }}"
    description: HDFS group