---
- name: ensure hadoop directory exists
  file:
    path: "{{ hadoop_path }}"
    state: directory

- name: Unzip Hadoop
  unarchive:
    src: "{{hadoop_download}}"
    dest: "{{ hadoop_path }}"
    remote_src: yes
    creates: "{{ hadoop_path }}/hadoop-{{ hadoop_version }}"
    group: "{{ hadoop_group }}"
    owner: "root"

