---
- name: Create HDFS Paths
  file: 
    path: "{{ item }}"
    owner: "{{ hdfs_user }}"
    group: "{{ hdfs_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ hdfs_create_path }}"



- include: install_hadoop.yml

- include: config_hadoop.yml

