---

- name: install Hadoop
  when: install_hadoop | default(true) # So we can depend on this role just for the vars, if nessesary
  block:

    - name: Create common dirs
      file:
        path: "{{ item }}"
        owner: "root"
        group: "{{ hadoop_group.name }}"
        state: directory
        mode: 0775
      with_items:
        - "{{ hadoop_log_dir }}"
        - "{{ hadoop_tmp }}"



    - name: ensure hadoop directory exists
      file:
        path: "{{ hadoop_path }}"
        state: directory


    - debug:
        msg: "Downloading hadoop from {{ hadoop_download }}"


    - name: Unzip Hadoop
      unarchive:
        src: "{{ hadoop_download }}"
        dest: "{{ hadoop_path }}"
        remote_src: yes
        creates: "{{ hadoop_home }}"
        group: "{{ hadoop_group.name }}"
        owner: "root"

    - name: "Link {{ hadoop_home }} to {{ current_hadoop_home }}"
      file:
        src: "{{ hadoop_home }}"
        dest: "{{ current_hadoop_home }}"
        state: link

- name: Configure Hadoop
  when: install_hadoop | default(true) and configure_hadoop | default(true)
  block:
    - name: Upload Hadoop config files
      template:
        src: "{{ item }}"
        dest: "{{ hadoop_config_path }}/"
        mode: 0644
        owner: "root"
        group: "{{ hadoop_group.name }}"
      with_fileglob:
        - "templates/hadoop_conf/*"

    - name: remove {{ hadoop_home }}/etc/hadoop
      file:
        path: "{{ hadoop_home }}/etc/hadoop"
        state: absent
    - name: symlink {{ hadoop_home }}/etc/hadoop to {{ hadoop_config_path }}
      file:
        src: "{{ hadoop_config_path }}"
        dest:  "{{ hadoop_home }}/etc/hadoop"
        owner: root
        group: "{{ hadoop_group.name }}"
        state: link
        force: true

    - name: Set the right permissions for container-executor
      file:
        path: "{{ hadoop_home }}/bin/container-executor"
        owner: root
        group: "{{ hadoop_group.name }}"
        mode: '6050'

    - name: install log4jSyslogWriter64k in classpath
      include_tasks: installLog4jSyslogAppender.yml
      vars:
        dest: "{{ hadoop_home }}/share/hadoop/common/lib/"
        owner:
          name: root
          group: "{{ hadoop_group.name }}"

    - name: Upload Hadoop daemon invoker Script
      template:
        src: "hadoop-invoker.sh"
        dest: "/usr/local/bin/"
        mode: "0755"
        owner: "root"
        group: "{{ hadoop_group.name }}"

    - name: Upload Hadoop profile files
      template:
        src: "{{ item }}"
        dest: "/etc/profile.d/"
        mode: 0644
        owner: "root"
        group: "{{ hadoop_group.name }}"
      with_fileglob:
        - "templates/profile.d/*"

    - name: Upload Hadoop YARN systemd services
      when: install_yarn | default(true)
      template:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        mode: 0644
        owner: "root"
        group: "root"
      with_fileglob:
        - "templates/systemd/yarn/*"

    - name: Upload Hadoop HDFS systemd services
      when: install_hdfs | default(true)
      template:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        mode: 0644
        owner: "root"
        group: "root"
      with_fileglob:
        - "templates/systemd/hdfs/*"

    - name: Upload Hadoop Mapreduce systemd services
      when: install_mapreduce | default(true)
      template:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        mode: 0644
        owner: "root"
        group: "root"
      with_fileglob:
        - "templates/systemd/mapreduce/*"


