---
- name: Create HDFS Paths
  file: 
    path: "{{ item }}"
    owner: "{{ hdfs_user }}"
    group: "{{ hdfs_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ hdfs_create_path }}"

- name: Create YARN Paths
  file:
    path: "{{ item }}"
    owner: "{{ yarn_user }}"
    group: "{{ hadoop_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ yarn_create_path }}"

- name: Create Zookeeper Paths
  file:
    path: "{{ item }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ hadoop_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ zookeeper_create_path }}"


- include: install_hadoop.yml
  when: install_hadoop

- include: config_hadoop.yml
  when: config_hadoop

- include: firewall.yml

- include: start_hdfs.yml
