---
- name: Create HDFS Paths
  file: 
    path: "{{ item }}"
    owner: "{{ hadoop_hdfs_user }}"
    group: "{{ group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ hadoop_hdfs_create_path }}"

- name: Create YARN Paths
  file:
    path: "{{ item }}"
    owner: "{{ hadoop_yarn_user }}"
    group: "{{ group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ hadoop_yarn_create_path }}"

- name: Create Zookeeper Paths
  file:
    path: "{{ item }}"
    owner: "{{ hadoop_zookeeper_user }}"
    group: "{{ group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ hadoop_zookeeper_create_path }}"


- include: install_hadoop.yml
  when: install_hadoop

- include: config_hadoop.yml
  when: config_hadoop

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: start_hadoop.yml
