---

- name: Stop node manager systemd service
  systemd:
    state: stopped
    daemon_reload: yes
    name: yarn_node_manager
    enabled: true



- name: Create data dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ yarn_user.name }}"
    group: "{{ yarn_user.group }}"
    mode: 0755
  with_items: "{{ yarn_data_dirs }}"

- name: Create other dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ yarn_user.name }}"
    group: "{{ yarn_user.group }}"
    mode: 0755
  with_items: #TODO get these configurable
    - /tmp/hadoop/yarn-nm-recovery/
    - /var/log/hadoop/yarn/userlogs


- name: (Re)Start node manager systemd service
  systemd:
    state: restarted
    daemon_reload: yes
    name: yarn_node_manager
    enabled: true

