---


default_wipe_hdfs: false
# hadoop basic vars
# Set a local file here, if you do not want to download it dynamicallyl
default_hadoop_version: "3.3.0"
default_hadoop_download: http://ftp.download-by.net/apache/hadoop/common/hadoop-{{hadoop_version}}/hadoop-{{hadoop_version}}.tar.gz
default_hadoop_path: "/usr/local/hadoop"
default_hadoop_home: "{{ hadoop_path }}/hadoop-{{ hadoop_version }}"

default_current_hadoop_home: "{{ hadoop_path }}/current"

default_hadoop_config_path: "/etc/hadoop/conf"
default_hadoop_tmp: "/tmp/hadoop"
default_hadoop_log_dir: "/var/log/hadoop"
default_hadoop_pid_dir: "/var/run/hadoop"



default_hdfs_namenode_memory: "4096m"
default_hdfs_datanode_memory: "2048m"

default_mapreduce_map_java_memory: "1536m"
default_mapreduce_map_yarn_memory: 2048
default_mapreduce_reduce_java_memory: "1536m"
default_mapreduce_reduce_yarn_memory: 2048
default_mapreduce_am_java_memory: "1536m"
default_mapreduce_am_yarn_memory: 2048
default_mapreduce_task_sort_memory: 1024

default_yarn_nodemanager_available_cpu_cores: 1
default_yarn_nodemanager_available_memory: 1024

default_yarn_scheduler_min_cpu_cores: 1
default_yarn_scheduler_max_cpu_cores: 2
default_yarn_scheduler_min_memory: 1024
default_yarn_scheduler_max_memory: 3072

#HDFS
default_hadoop_dfs_name: "/hdfs/dfs/name"
default_hadoop_dfs_journal: "/hdfs/dfs/journal"


default_hdfs_name: "KAC"

default_hdfs_data_dirs: []
#  - /data/sdb1/hdfs
#  - /data/sdc1/hdfs
#  - /data/sdd1/hdfs
#  - /data/sde1/hdfs
#  - /data/sdf1/hdfs
#  - /data/sdg1/hdfs

hdfs_data_dirs_joined:  "{{ hdfs_data_dirs | join(',') }}"


#YARN

default_yarn_timeline_store: "/hadoop/yarn/timeline"


yarn_timelineserver: "{{ groups['yarn_timeline_servers'] | first }}"


default_yarn_data_dirs: []
#  - /data/sdb1/yarn
#  - /data/sdc1/hdfs
#  - /data/sdd1/hdfs
#  - /data/sde1/hdfs
#  - /data/sdf1/hdfs
#  - /data/sdg1/hdfs

yarn_data_dirs_joined:  "{{ yarn_data_dirs | join(',') }}"

default_yarn_application_logs_dir: "{{ hadoop_log_dir }}/{{ yarn_user }}/application-logs/"
#yarn_user_logs: "/hadoop/yarn/

#TODO more than one?
mapreduce_history_server_host: "{{ groups['mapreduce_history_servers'] | first }}"
default_mapreduce_create_path:
  - "/hadoop/mapreduce"



zookeeper_quorum: "{{ groups['zookeeper_servers'] | zip_longest([], fillvalue=zookeeper_port) | map('join', ':') | join(',') }}"