## This playbook creates the hosts as virtual VMs in Ovirt

- name: oVirt ansible collection
  hosts: hostgroup_VMs
  gather_facts: False
  serial: 1 # Only create and run 1 at a time.
  # This is nessesary to set the network up correctly, as otherwise the temp ips will clash
  roles:
    - ovirt_new_vm
  collections: # This require the ovirt-ansible plugin installed. See ovirt_sdk_setup.sh
    - ovirt.ovirt
    - community.general


- name: oVirt ansible collection
  hosts: hostgroup_VMs
  gather_facts: False
  become: yes
  become_user: root
  remote_user: root
  tasks:
    - name: "Wait 600 seconds for host to become reachable/usable"
      wait_for_connection:
        delay: 0 # Number of seconds to wait before starting to poll.
        timeout: 600 # Maximum number of seconds to wait for.
        sleep: 2 # Number of seconds to sleep between checks.
        connect_timeout: 5 # Maximum number of seconds to wait for a connection to happen before closing and retrying.
