# Enable the {{sealbin_user}} account and disable ssh logins to root
- hosts: hostgroup_all:!localhost
  remote_user: root
  gather_facts: false
  ignore_unreachable: yes
  roles:
    - role: ansible_account
  tasks:
    - meta: clear_host_errors
  collections:
    - ansible.posix

- name: gather facts from all
  hosts: hostgroup_all
  gather_facts: True