
# Enable the {{ sealbin_user }} account, which will be used as the ansible user in all subsequent playbooks

- hosts: hostgroup_all:!localhost
  remote_user: root
  gather_facts: false
  ignore_unreachable: yes
  roles:
    - role: ansible_account
  tasks:
    - name: Clear Host Errors
      meta: clear_host_errors
  collections:
    - ansible.posix

- hosts: localhost
  connection: local
  gather_facts: false
  ignore_unreachable: yes
  roles:
    - role: ansible_account
  tasks:
    - name: Clear Host Errors
      meta: clear_host_errors
  collections:
    - ansible.posix


- name: gather facts from all
  hosts: hostgroup_all
  gather_facts: True
