



- hosts: ipaclients
  throttle: 5 # It seems that if every node tries to register at the same time, some of them will fail
  roles:
    - role: ipaclient_setup # Set up the ipa clients
  collections:
    - freeipa.ansible_freeipa


# Now that the hosts have been added as ipa clients, we can setup the kerberos services
- hosts: ipaserver
  roles:
    - role: ipa_system_users
    - role: ipa_sudorules
    - role: ipa_syshomes
    - role: ipa_autohomes
  collections:
    - freeipa.ansible_freeipa

