
- hosts: all
  remote_user: root
  roles:
    - ansible_account


- hosts: zabbix_nodes
  roles:
    - role: zabbix_agent



- hosts: ipaclients
  throttle: 5
  roles:
    - role: updated
    - role: java_1_8_installed # Install java
    - role: ipaclient_setup # Set up the ipa clients
    - role: firewalled # Set up the firewall


# Now that the hosts have been added as ipa clients, we can setup the kerberos services
- hosts: ipaserver
  vars:
    create_users: yes
    create_certificates: yes
    create_ipa_services: yes
    create_keytabs: yes
  roles:
    - role: yak_user_manager
      when: create_users | bool
    - role: ssl_certificates_creator
      when: create_certificates | bool
    - role: ipa_service_definitions
      when: create_ipa_services | bool
    - role: kerberos_system_user_keytabs_create
      when: create_keytabs | bool

