
# Enable the {{sealbin_user}} account and disable ssh logins to root
- hosts: all:!localhost
  remote_user: root
  ignore_unreachable: yes
  roles:
    - ansible_account
  tasks:
    - meta: clear_host_errors



- hosts: hadoop_nodes
  roles:
    - role: updated
    - role: java_1_8_installed
    - role: firewalled


- hosts: zabbix_nodes
  roles:
    - role: zabbix_agent


- hosts: ipaclients
  throttle: 5 # It seems that if every node tries to register at the same time, some of them will fail
  roles:
    - role: ipaclient_setup # Set up the ipa clients


# Now that the hosts have been added as ipa clients, we can setup the kerberos services
- hosts: ipaserver
  roles:
    - role: ipa_system_users
    - role: ipa_sudorules
    - role: ipa_syshomes
    - role: ipa_autohomes
    - role: ssl_certificates_creator
    - role: ipa_service_definitions
    - role: kerberos_system_user_keytabs_create

# And now that the ipa server is ready, we can setup services and ssl
- hosts: hadoop_nodes
  roles:
    - role: ssl_certificates_recipient #Upload ssl certificates to host
    - role: kerberos_service_keytabs #Create the service keytabs
    - role: kerberos_system_user_keytabs
