
# Enable the {{sealbin_user}} account and disable ssh logins to root
- hosts: all:!localhost
  remote_user: root
  ignore_unreachable: yes
  roles:
    - ansible_account
  tasks:
    - meta: clear_host_errors



- hosts: hadoop_nodes
  roles:
    - role: updated
    - role: java_1_8_installed
    - role: firewalled


- hosts: zabbix_nodes
  roles:
    - role: zabbix_agent


- hosts: ipaclients
  throttle: 5 # It seems that if every node tries to register at the same time, some of them will fail
  roles:
    - role: ipaclient_setup # Set up the ipa clients


# Now that the hosts have been added as ipa clients, we can setup the kerberos services
- hosts: ipaserver
  vars:
    # These vars allow us to turn of some of these features when running
    create_users: yes
    create_certificates: yes
    create_ipa_services: yes
    create_keytabs: yes
  roles:
    - role: yak_user_manager
      when: create_users | bool
    - role: ssl_certificates_creator
      when: create_certificates | bool
    - role: ipa_service_definitions
      when: create_ipa_services | bool
    - role: kerberos_system_user_keytabs_create
      when: create_keytabs | bool

# And now that the ipa server is ready, we can setup services and ssl
- hosts: hadoop_nodes
  roles:
    - role: ssl_certificates_recipient #Upload ssl certificates to host
    - role: kerberos_service_keytabs #Create the service keytabs
    - role: kerberos_system_user_keytabs
