
#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all:!localhost
  gather_facts: yes


- hosts: hostgroup_ipaserver
  roles:
    - role: ipa_system_users

    - role: ipa_syshomes

    - role: ipa_autohomes

  collections:
    - freeipa.ansible_freeipa

- hosts: hostgroup_ipaclients
  throttle: 5 # It seems that if every node tries to register at the same time, some of them will fail
  roles:
    - role: ipaclient_setup # Set up the ipa clients
  collections:
    - freeipa.ansible_freeipa


- hosts: hostgroup_ipaserver
  roles:
    - role: ipa_sudorules
  collections:
    - freeipa.ansible_freeipa
