
#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all:!localhost
  gather_facts: yes


- hosts: hostgroup_ansible_host
  roles:
    - role: ssl_certificates_creator

- hosts: hostgroup_rsyslog_server
  vars:
    # rsyslog server is not a ipaclient, so does not have the hadoop group
    # So this is nessesary to ensure that what should have been owned by hadoop is now owned by root.
    hadoop_group:
      name: root
    jupyterhub_user:
      name: root
  roles:
    - role: ssl_certificates_recipient #Upload ssl certificates to host

- hosts: hostgroup_hadoop_nodes
  roles:
    - role: ssl_certificates_recipient #Upload ssl certificates to host
