
#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes

#Setup the rsyslog server
- hosts: hostgroup_rsyslog_server
  roles:
    - role: rsyslog_server


#Install the syslog client on all hadoop nodes, so they can log to rsyslog
- hosts: hostgroup_hadoop_nodes
  roles:
    - role: rsyslog_client
