
#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes

# The order here is important


# Now that the hosts have been added as ipa clients, we can setup the kerberos services
# See 20_playbook_ipa.yml
- hosts: hostgroup_ipaserver
  roles:
    - role: ipa_service_definitions # Create Kerberos service definitions in FreeIPA
  collections:
    - freeipa.ansible_freeipa

- hosts: hostgroup_ansible_host
  roles:
    - role: kerberos_system_user_keytabs_create # Create the keytabs for the cluster-wide system users
  collections:
    - freeipa.ansible_freeipa


- hosts: hostgroup_hadoop_nodes
  roles:
    - role: kerberos_service_keytabs #Create the node-specific service keytabs on each of the nodes
    - role: kerberos_system_user_keytabs # Distribute the system user keytabs from the ansible host to the relevant nodes

