
#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes

# The order here is important


# Now that the hosts have been added as ipa clients, we can setup the kerberos services
#- hosts: hostgroup_ipaserver
#  roles:
#    - role: ipa_service_definitions
#  collections:
#    - freeipa.ansible_freeipa

# Now that the hosts have been added as ipa clients, we can setup the kerberos services
- hosts: hostgroup_ansible_host
  roles:
    - role: kerberos_system_user_keytabs_create
  collections:
    - freeipa.ansible_freeipa


# And now that the ipa server is ready, we can setup services and ssl
- hosts: hostgroup_hadoop_nodes
  roles:
    - role: kerberos_service_keytabs #Create the service keytabs
    - role: kerberos_system_user_keytabs

