# The order here is important


# And now that the ipa server is ready, we can setup services and ssl
- hosts: hadoop_nodes
  roles:
    - role: ssl_certificates_recipient #Upload ssl certificates to host
    - role: kerberos_service_keytabs #Create the service keytabs
    - role: kerberos_system_user_keytabs

# HDFS HA requires zookeepers
- hosts: zookeeper_servers
  roles:
    - zookeeper_server

# HDFS

# The journalnodes must exist before the namenodes can run
- hosts: hdfs_journalnodes
  roles:
    - hdfs_journalnode

# The namenodes do not require datanodes, but the datanodes require namenodes
- hosts: hdfs_namenodes
  roles:
    - hdfs_namenode

# The datanodes become unhappy if they cannot connect to a namenode when starting up, so install them after the
#   namenodes
- hosts: hdfs_datanodes
  roles:
    - hdfs_datanode

# YARN

- hosts: yarn_timeline_servers
  roles:
    - yarn_timeline_server


- hosts: yarn_node_managers
  roles:
    - yarn_node_manager


- hosts: yarn_resource_managers
  roles:
    - yarn_resource_manager


# MapReduce


- hosts: mapreduce_history_servers
  roles:
    - mapreduce_history_server

# Spark

- hosts: spark_history_servers
  roles:
    - role: spark_history_server
