
#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes

# The order here is important


# HDFS HA requires zookeepers
- hosts: hostgroup_zookeeper_servers
  roles:
    - role: zookeeper_server
