
#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes



# MapReduce is not really a separate system, but rather a framework for YARN jobs

# History server handle log aggregation for mapreduce jobs. There is some not-entirely-known interaction between
#  hadoop_mapreduce_history_server and hadoop_yarn_timeline_server, and they should usually just be deployed on the
#  same host
- hosts: hostgroup_mapreduce_history_servers
  roles:
    - role: hadoop_mapreduce_history_server
