#Just a cutdown 30.playbook-hadoop-setyp.yml that only sets up yarn

#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes

# The order here is important

# YARN

- hosts: hostgroup_yarn_timeline_servers
  roles:
    - role: hadoop_yarn_timeline_server


- hosts: hostgroup_yarn_node_managers
  roles:
    - role: hadoop_yarn_node_manager


- hosts: hostgroup_yarn_resource_managers
  roles:
    - role: hadoop_yarn_resource_manager


# MapReduce


- hosts: hostgroup_mapreduce_history_servers
  roles:
    - role: hadoop_mapreduce_history_server

# Spark

- hosts: hostgroup_spark_history_servers
  roles:
    - role: spark_history_server
