---


#  Et projekt består af disse "komponenter"

#    En projekt maskine
#
- name: oVirt ansible collection
  #  https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html#common-patterns
  hosts: hostgroup_project_nodes:&hostgroup_VMs
  gather_facts: False
#  serial: 1 # Only create and run 1 at a time.
#  # This is nessesary to set the network up correctly, as otherwise the temp ips will clash
  roles:
    - role: ovirt_new_vm
  collections: # This require the ovirt-ansible plugin installed. See ovirt_sdk_setup.sh
    - ovirt.ovirt
    - community.general


- name: "Enable the {{sealbin_user}} ansible user account"
  hosts: hostgroup_project_nodes
  remote_user: root
  ignore_unreachable: yes
  roles:
    - role: ansible_account
  tasks:
    - meta: clear_host_errors
  collections:
    - ansible.posix


#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes


# Regenerate SSL certificates, if any new hosts were added
- hosts: hostgroup_ipaserver
  roles:
    - role: ssl_certificates_creator


- name: Basic setup including ipa client
  hosts: hostgroup_project_nodes
  roles:
    - role: updated
    - role: java_1_8_installed
    - role: ipaclient_setup
    - role: ssl_certificates_recipient # Upload new ssl certificates, if needed
    - role: rsyslog_client
    - role: zabbix_agent
  collections:
#    - community.zabbix If this is uncommented, you will get errors about Springdale.yml
    - freeipa.ansible_freeipa

#      med X2go
#      med RStudio
#      og måske Jupyter
- name: Rstudio/Jupyterhub
  hosts: hostgroup_project_nodes
  roles:
    - role: spark_client
    - role: rstudio_server
    - role: jupyterhub
    - role: x2go
  collections:
    - freeipa.ansible_freeipa

# Hadoop is installed now, so ensure that the keytabs are in place
- hosts: hostgroup_project_nodes
  roles:
    - role: kerberos_service_keytabs #Create the service keytabs
    - role: kerberos_system_user_keytabs



#  En brugergruppe
#  1+ Brugere
#  en HBAC regel
- name: Users and groups
  hosts: hostgroup_ipaserver
  roles:
    - role: ipa_projects_and_groups
  collections:
    - freeipa.ansible_freeipa



#    TODO Home Dir logging per project





#    En YARN queue
- hosts: hostgroup_yarn_timeline_servers
  serial: 1
  roles:
    - role: hadoop_yarn_timeline_server
- hosts: hostgroup_yarn_node_managers
  serial: 1
  roles:
    - role: hadoop_yarn_node_manager
- hosts: hostgroup_yarn_resource_managers
  serial: 1
  roles:
    - role: hadoop_yarn_resource_manager

