---


#  Et projekt består af disse "komponenter"


#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes


- name: Spark Client
  hosts: hostgroup_project_nodes
  roles:
    - role: spark_client


# Hadoop is installed now, so ensure that the keytabs are in place
- hosts: hostgroup_project_nodes
  roles:
    - role: kerberos_service_keytabs #Create the service keytabs
    - role: kerberos_system_user_keytabs