---


#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes


#  En brugergruppe
#  1+ Brugere
#  en HBAC regel
- name: Users and groups
  hosts: hostgroup_ipaserver
  roles:
    - role: ipa_projects_and_groups
  collections:
    - freeipa.ansible_freeipa

