---


#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes


# Setup users and groups
# * Create project group in FreeIPA
# * Create project dir in HDFS, with correct permissions
# * Create users in FreeIPA
# * mkdir and chown user homes in HDFS
# * Create FreeIPA HBAC (Host Based Access Control) rules to ensure users can log into their project node
- name: Users and groups
  hosts: hostgroup_ipaserver
  roles:
    - role: ipa_projects_and_groups
  collections:
    - freeipa.ansible_freeipa

