# This playbook sets up a hdfs cluster with kerberos and ssl

# Prerequisites
# - the hosts must have been made and be freeipa clients
# - The users must have been made
# - playbook-ssl-certificates.yml
# - playbook-kerberos-services.yml
# - playbook-zookeeper.yml
#
#
#- hosts: journalnodes
#  vars_files:
#    - vars/var_java.yml
#    - vars/var_ports.yml
#    - vars/var_hadoop.yml
#    - vars/var_kerberos.yml
#    - vars/var_ipa.yml
#  roles:
#    - hdfs_journalnode


- hosts: datanodes
  vars_files:
    - vars/var_java.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_kerberos.yml
    - vars/var_ipa.yml
  roles:
    - hdfs_datanode



#
#- hosts: namenodes
#  vars_files:
#    - vars/var_java.yml
#    - vars/var_ports.yml
#    - vars/var_hadoop.yml
#    - vars/var_kerberos.yml
#    - vars/var_ipa.yml
#  roles:
#    - hdfs_namenode
