
- hosts: hadoop_nodes
  roles:
    - role: capacity_scheduler
  tasks:
    - name: debug output
      debug:
        msg: "{{lookup('vars', *(projects | map(attribute='name'))) | map(attribute='project_ipa') | list }}"


