# This playbook sets up a hdfs cluster with kerberos and ssl

# Prerequisites
# - the hosts must have been made and be freeipa clients
# - The users must have been made
# - playbook-ssl-certificates.yml
# - playbook-kerberos-services.yml
# - playbook-zookeeper.yml
#
#

# The order here is important

  # The journalnodes must exist before the namenodes can run
- hosts: hdfs_journalnodes
  vars_files:
    - vars/var_java.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_ssl.yml
    - vars/var_kerberos.yml
    - vars/var_ipa.yml
  roles:
    - hdfs_journalnode

  # The namenodes do not require datanodes
- hosts: hdfs_namenodes
  vars_files:
    - vars/var_java.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_ssl.yml
    - vars/var_kerberos.yml
    - vars/var_ipa.yml
  roles:
    - hdfs_namenode

  # The datanodes become unhappy if they cannot connect to a namenode when starting up
- hosts: hdfs_datanodes
  vars_files:
    - vars/var_java.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_ssl.yml
    - vars/var_kerberos.yml
    - vars/var_ipa.yml
  roles:
    - hdfs_datanode
