- hosts: ipaclients
  vars_files:
    - vars/var_java.yml
    - vars/var_ipa.yml
    - vars/var_sensitive.yml
    - vars/var_hadoop.yml
    - vars/var_ssl.yml
    - vars/var_ports.yml
  vars:
    letters: "abcdefghicklmopqrstuvwxyz"
  tasks:
    - name: "include role: updated"
      include_role:
        name: updated

    - name: format extra disks
      include: tasks/task_format_disk.yml mount="{{item.mount}}" device="sd{{letters[idx+1]}}"
      when: host_disks is defined
      loop: "{{host_disks}}"
      loop_control:
        index_var: idx
  roles:
    - role: ipaclient_setup
    - role: kerberos
    - role: java
    - role: ssl_certificates
    - role: firewall_disabled

