# YARN will fail if the HDFS is still in safe mode
- hosts: hostgroup_hdfs_namenodes
  vars:
    - keytab_dir:  "/etc/security/keytabs"
    - kinit_principal: "{{user_prefix}}hdfs"
  tasks:
    - import_tasks: tasks/kinit_keytab.yml
    - name: wait for HDFS to leave safemode
      changed_when: false
      shell:
        cmd: |
          source /etc/profile.d/hadoop.sh
          source /etc/profile.d/kerberos.sh
          hdfs dfsadmin -safemode wait


## YARN

- hosts: hostgroup_yarn_timeline_servers
  serial: 1
  tasks:
    - name: restart timeline_server
      ansible.builtin.systemd:
        state: restarted
        name: yarn_timeline_server
        daemon_reload: yes


- hosts: hostgroup_yarn_node_managers
  serial: 1
  tasks:
    - name: restart node manager
      ansible.builtin.systemd:
        state: restarted
        name: yarn_node_manager
        daemon_reload: yes


- hosts: hostgroup_yarn_resource_managers
  serial: 1
  tasks:
    - name: restart resource manager
      ansible.builtin.systemd:
        state: restarted
        name: yarn_resource_manager
        daemon_reload: yes


## MapReduce

- hosts: hostgroup_mapreduce_history_servers
  serial: 1
  tasks:
    - name: restart mapreduce_historyserver
      ansible.builtin.systemd:
        state: restarted
        name: mapreduce_history_server
        daemon_reload: yes


## Spark


- hosts: hostgroup_spark_history_servers
  serial: 1
  tasks:
    - name: (Re)Start Spark History Server systemd service
      ansible.builtin.systemd:
        state: restarted
        name: spark_history_server
        daemon_reload: yes


