# This playbook sets up a hdfs cluster with kerberos and ssl

# Prerequisites
# - the hosts must have been made and be freeipa clients
# - The users must have been made
# - playbook-ssl-certificates.yml
# - playbook-kerberos-services.yml
# - playbook-zookeeper.yml

- hosts: hdfs_journal
  vars_files:
    - vars/var_basic.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_kerberos.yml
    - vars/hadoop_config_files/var_core_site.yml
    - vars/hadoop_config_files/var_hdfs_site.yml
    - vars/hadoop_config_files/var_mapred_site.yml
  roles:
    - journalnode


- hosts: workers
  vars_files:
    - vars/var_basic.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_kerberos.yml
    - vars/hadoop_config_files/var_core_site.yml
    - vars/hadoop_config_files/var_hdfs_site.yml
    - vars/hadoop_config_files/var_mapred_site.yml
  roles:
    - datanode




- hosts: hdfs_namenode
  vars_files:
    - vars/var_basic.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_kerberos.yml
    - vars/hadoop_config_files/var_core_site.yml
    - vars/hadoop_config_files/var_hdfs_site.yml
    - vars/hadoop_config_files/var_mapred_site.yml
  roles:
    - namenode
