
- hosts: timeline_servers
  vars_files:
    - vars/var_java.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_kerberos.yml
    - vars/var_ssl.yml
    - vars/var_ipa.yml
  roles:
    - yarn_timeline_server


- hosts: nodemanagers
  vars_files:
    - vars/var_java.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_kerberos.yml
    - vars/var_ssl.yml
    - vars/var_ipa.yml
  roles:
    - yarn_node_manager


- hosts: resource_managers
  vars_files:
    - vars/var_java.yml
    - vars/var_ports.yml
    - vars/var_hadoop.yml
    - vars/var_kerberos.yml
    - vars/var_ssl.yml
    - vars/var_ipa.yml
  roles:
    - yarn_resource_manager


