- hosts: ipaclients
  vars_files:
    - vars/var_ipa.yml
    - vars/var_ipa_sensitive.yml
  roles:
    - role: ipaclient
    - role: kerberos
  tasks:
    - name: create {{ipaclient_autohome_dir}}
      file:
        path: "{{ipaclient_autohome_dir}}"
        state: directory
        mode: '0755'
    - name: create {{ipaclient_syshome_dir}}
      file:
        path: "{{ipaclient_syshome_dir}}"
        state: directory
        mode: '0755'
    - name: "Mount {{ipaclient_syshome_dir}}"
      mount:
        path: "{{ipaclient_syshome_dir}}"
        src: "{{ipa_server}}:{{ipaserver_syshome_dir}}"
        fstype: "nfs4"
        opts: "rw,defaults,_netdev,hard,intr,_netdev"
        state: mounted
