
#The stuff below expect us to have facts about the ansible_fqdn of each host, so ensure that we have gathered these facts
- name: Gather facts from all to ensure we have their fqdn names
  hosts: hostgroup_all
  gather_facts: yes

# And now that the ipa server is ready, we can setup services and ssl
- hosts: hostgroup_yarn_resource_managers, hostgroup_yarn_node_managers
  roles:
    - role: hadoop


