

# And now that the ipa server is ready, we can setup services and ssl
- hosts: hostgroup_hadoop_nodes
  roles:
    - role: ssl_certificates_recipient #Upload ssl certificates to host
    - role: kerberos_service_keytabs #Create the service keytabs
    - role: kerberos_system_user_keytabs
    - role: hadoop
    - role: zookeeper
    - role: spark

