- hosts: workers
  become: yes
  vars_files:
    - vars/var_basic.yml
    - vars/var_hadoop.yml
    - vars/var_core_site.yml
    - vars/var_hdfs_site.yml
  vars:
    open_firewall: false
    disable_firewall: true
    install_hadoop: true
    config_hadoop: true
  roles:
    - java
    - hadoop


