# Everything runs with serial: 1 here to ensure that the services can fail-over while restarting

- hosts: hostgroup_zookeeper_servers
  serial: 1
  tasks:
    - name: restart zookeeper_server
      ansible.builtin.systemd:
        state: restarted
        name: zookeeper
        daemon_reload: yes


- hosts: hostgroup_hdfs_journalnodes
  serial: 1
  tasks:
    - name: restart journalnode
      ansible.builtin.systemd:
        state: restarted
        name: hdfs_journalnode
        daemon_reload: yes


  # The namenodes do not require datanodes
- hosts: hostgroup_hdfs_namenodes
  serial: 1
  tasks:
    - name: restart namenode
      ansible.builtin.systemd:
        state: restarted
        name: hdfs_namenode
        daemon_reload: yes



  # The datanodes become unhappy if they cannot connect to a namenode when starting up
- hosts: hostgroup_hdfs_datanodes
  serial: 1
  tasks:
    - name: restart datanode
      ansible.builtin.systemd:
        state: restarted
        name: hdfs_datanode
        daemon_reload: yes

# YARN will fail if the HDFS is still in safe mode
- hosts: hostgroup_hdfs_namenodes
  vars:
    - keytab_dir:  "/etc/security/keytabs"
    - kinit_principal: "{{ user_prefix }}hdfs"
  tasks:
    - import_tasks: tasks/kinit_keytab.yml
    - name: wait for HDFS to leave safemode
      changed_when: false
      shell:
        cmd: |
          source /etc/profile.d/hadoop.sh
          source /etc/profile.d/kerberos.sh
          hdfs dfsadmin -safemode wait

