

- hosts: proj000.adm.yak2.net
  roles:
    - capacity_scheduler
  tasks:
#    - debug:
#        msg: "{{yarn_queues}}"
    - debug:
        msg: "{{capacity_queues | map(attribute='longname') | list}}"
