

# Now that the hosts have been added as ipa clients, we can setup the kerberos services
- hosts: proj000.yak2.net
  roles:
    - syslog_config
  tasks:
    - debug:
        msg: "{{ groups['hdfs_datanodes'] | map('extract',hostvars, 'ansible_fqdn') | first }}"
    - debug:
        msg: "{{ groups['all'] }}"
    - debug:
        msg: "{{ groups['all'] | map('extract',hostvars, 'ansible_fqdn') | list }}"
#    - debug:
#        msg: "{{ hostvars | selectattr('group_names', 'contains', 'rsyslog_server') | list}}"
