
- hosts: hdfs_journalnodes
  serial: 1
  tasks:
    - name: restart journalnode
      systemd:
        state: restarted
        name: hdfs_journalnode
        daemon_reload: yes


  # The namenodes do not require datanodes
- hosts: hdfs_namenodes
  serial: 1
  tasks:
    - name: restart namenode
      systemd:
        state: restarted
        name: hdfs_namenode
        daemon_reload: yes



  # The datanodes become unhappy if they cannot connect to a namenode when starting up
- hosts: hdfs_datanodes
  serial: 1
  tasks:
    - name: restart datanode
      systemd:
        state: restarted
        name: hdfs_datanode
        daemon_reload: yes

