# Everything runs with serial: 1 here to ensure that the services can fail-over while restarting

- hosts: hostgroup_zookeeper_servers
  serial: 1
  tasks:
    - name: restart zookeeper_server
      ansible.builtin.systemd:
        state: restarted
        name: zookeeper
        daemon_reload: yes


- hosts: hostgroup_hdfs_journalnodes
  serial: 1
  tasks:
    - name: restart journalnode
      ansible.builtin.systemd:
        state: restarted
        name: hdfs_journalnode
        daemon_reload: yes


  # The namenodes do not require datanodes
- hosts: hostgroup_hdfs_namenodes
  serial: 1
  tasks:
    - name: restart namenode
      ansible.builtin.systemd:
        state: restarted
        name: hdfs_namenode
        daemon_reload: yes



  # The datanodes become unhappy if they cannot connect to a namenode when starting up
- hosts: hostgroup_hdfs_datanodes
  serial: 1
  tasks:
    - name: restart datanode
      ansible.builtin.systemd:
        state: restarted
        name: hdfs_datanode
        daemon_reload: yes

## YARN

- hosts: hostgroup_yarn_timeline_servers
  serial: 1
  tasks:
    - name: restart timeline_server
      ansible.builtin.systemd:
        state: restarted
        name: yarn_timeline_server
        daemon_reload: yes


- hosts: hostgroup_yarn_node_managers
  serial: 1
  tasks:
    - name: restart node manager
      ansible.builtin.systemd:
        state: restarted
        name: yarn_node_manager
        daemon_reload: yes


- hosts: hostgroup_yarn_resource_managers
  serial: 1
  tasks:
    - name: restart resource manager
      ansible.builtin.systemd:
        state: restarted
        name: yarn_resource_manager
        daemon_reload: yes


## MapReduce

- hosts: hostgroup_mapreduce_history_servers
  serial: 1
  tasks:
    - name: restart mapreduce_historyserver
      ansible.builtin.systemd:
        state: restarted
        name: mapreduce_history_server
        daemon_reload: yes


## Spark


- hosts: hostgroup_spark_history_servers
  serial: 1
  tasks:
    - name: (Re)Start Spark History Server systemd service
      ansible.builtin.systemd:
        state: restarted
        name: spark_history_server
        daemon_reload: yes


