# The order here is important

# The namenodes do not require datanodes, but the datanodes require namenodes
- hosts: proj000.yak2.net
  vars_files:
    -  vars/var_sensitive.yml
  roles:
    - jupyterhub