
- hosts: yarn_timeline_servers
  serial: 1
  tasks:
    - name: restart timeline_server
      systemd:
        state: restarted
        name: yarn_timeline_server


- hosts: yarn_node_managers
  serial: 1
  tasks:
    - name: restart node manager
      systemd:
        state: restarted
        name: yarn_node_manager


- hosts: yarn_resource_managers
  serial: 1
  tasks:
    - name: restart resource manager
      systemd:
        state: restarted
        name: yarn_resource_manager