---
#- hosts: all
#  remote_user: root
#  tasks:
#    - command: /bin/sleep 15
#      async: 45
#      poll: 5

- hosts: hostgroup_all:!localhost
  remote_user: root
#  serial: 1
  roles:
    - role: log4jshell
      log4shell_scan_path:
        - /opt/
        - /usr/
        - /var/lib/


# TODO Check for war-files like this
#  ansible -i hosts/KAC hostgroup_all -a 'bash -c "find /usr -name *.war -size +10k | xargs -r -i unzip -l {} | (grep log4j-core || echo clean) | grep -v log4j-core  "' -u root

