
- hosts: yarn_timeline_servers
  roles:
    - yarn_timeline_server


- hosts: yarn_node_managers
  roles:
    - yarn_node_manager


- hosts: yarn_resource_managers
  roles:
    - yarn_resource_manager


