# The order here is important

# The namenodes do not require datanodes, but the datanodes require namenodes
- hosts: proj000.yak2.net
  vars:
    install_hadoop: false
  roles:
    - rstudio_server
    - jupyterhub