# Everything runs with serial: 1 here to ensure that the services can fail-over while restarting

- hosts: zookeeper_servers
  serial: 1
  tasks:
    - name: restart zookeeper_server
      systemd:
        state: restarted
        name: zookeeper
        daemon_reload: yes


- hosts: hdfs_journalnodes
  serial: 1
  tasks:
    - name: restart journalnode
      systemd:
        state: restarted
        name: hdfs_journalnode
        daemon_reload: yes


  # The namenodes do not require datanodes
- hosts: hdfs_namenodes
  serial: 1
  tasks:
    - name: restart namenode
      systemd:
        state: restarted
        name: hdfs_namenode
        daemon_reload: yes



  # The datanodes become unhappy if they cannot connect to a namenode when starting up
- hosts: hdfs_datanodes
  serial: 1
  tasks:
    - name: restart datanode
      systemd:
        state: restarted
        name: hdfs_datanode
        daemon_reload: yes

## YARN

- hosts: yarn_timeline_servers
  serial: 1
  tasks:
    - name: restart timeline_server
      systemd:
        state: restarted
        name: yarn_timeline_server
        daemon_reload: yes


- hosts: yarn_node_managers
  serial: 1
  tasks:
    - name: restart node manager
      systemd:
        state: restarted
        name: yarn_node_manager
        daemon_reload: yes


- hosts: yarn_resource_managers
  serial: 1
  tasks:
    - name: restart resource manager
      systemd:
        state: restarted
        name: yarn_resource_manager
        daemon_reload: yes


## MapReduce

- hosts: mapreduce_history_servers
  serial: 1
  tasks:
    - name: restart mapreduce_historyserver
      systemd:
        state: restarted
        name: mapreduce_history_server
        daemon_reload: yes


## Spark


- hosts: spark_history_servers
  serial: 1
  tasks:
    - name: Start Spark History Server process
      systemd:
        state: restarted
        name: spark_history_server
        daemon_reload: yes


