---

#These are the ansible galaxy collections needed for this collection of playbooks and roles

collections:
  - name: community.zabbix
    version: 1.4.0
  - name: community.postgresql

  - name: ovirt.ovirt

  - name: freeipa.ansible_freeipa

  - name: community.general
    version: 3.7.0

  - name: ansible.posix
    version: 1.3.0

  - name: community.crypto

  - name: claranet.log4shell
