---


- name: Upload spark config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ spark_config_path }}/"
    mode: 0640
    owner: "root"
    group: "{{ spark_user.group }}"
  with_fileglob:
    - "templates/spark_conf/*"



- name: Upload Spark invoker Script
  ansible.builtin.template:
    src: "spark-invoker.sh"
    dest: "/usr/local/bin/"
    mode: "0755"
    owner: "root"
    group: "{{ spark_user.group }}"


- name: Upload Spark systemd services
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: 0644
    owner: "root"
    group: "root"
  with_fileglob:
    - "templates/systemd/*"



- name: create basic directory structure
  become: yes
  become_user: "{{ hdfs_user.name }}"
  shell:
    cmd: |
      set -e # Fail on anything
      source /etc/profile.d/hadoop.sh
      source /etc/profile.d/kerberos.sh

      kinit -kt {{ keytab_dir }}/{{ hdfs_user.name }}.headless.keytab {{ hdfs_user.name }}

      hdfs dfs -mkdir -p {{ spark_eventLog_dir }}

      hdfs dfs -chown -R {{ spark_user.name }}:{{ hadoop_group.name }}  {{ spark_eventLog_dir }};

      hdfs dfs -chmod 777 {{ spark_eventLog_dir }};

      kdestroy


- name: (Re)Start Spark History Server systemd service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: true
    name: spark_history_server

