---


- name: Copy spark config files
  template:
    src: "{{ item }}"
    dest: "{{ spark_config_path }}/"
    mode: 0640
    owner: "root"
    group: "{{ spark_group }}"
  with_fileglob:
    - "templates/spark_conf/*"



- name: Copy Spark invoker Script
  template:
    src: "spark-invoker.sh"
    dest: "/usr/local/bin/"
    mode: "0755"
    owner: "root"
    group: "{{ spark_group }}"


- name: Copy Spark systemd services
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: 0644
    owner: "root"
    group: "root"
  with_fileglob:
    - "templates/systemd/*"


- name: Start Spark History Server process
  systemd:
    state: restarted
    daemon_reload: yes
    name: spark_history_server

