---


- name: Stop datanode process
  systemd:
    state: stopped
    daemon_reload: yes
    name: hdfs_datanode
    enabled: true
  when: wipe_hdfs | bool

- name: Wipe data
  file:
    path: "{{item}}"
    state: absent
  when: wipe_hdfs | bool
  with_items: "{{hdfs_data_dirs}}"


- name: Create data dir
  file:
    path: "{{item}}"
    state: directory
    owner: "{{hdfs_user.user}}"
    group: "{{hdfs_user.group}}"
    mode: 0750
  with_items: "{{hdfs_data_dirs}}"


- name: Start datanode process
  throttle: 1
  systemd:
    state: restarted
    daemon_reload: yes
    name: hdfs_datanode
    enabled: true
