---

- name:  Create VM
  include_tasks: create_vm.yml

#
#- name:  Open NIC 2
#  include_tasks: open_nic2.yml


- name: format+mount extra disks
  include: task_format_disk.yml
  vars:
    mount: "{{item.mount}}"
    device: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_{{(attached_disks.results[idx]['id'])[0:20]}}"
  when: host_disks is defined
  loop: "{{host_disks}}"
  loop_control:
    index_var: idx