---

- name:  Create VM
  include_tasks: create_vm.yml


- name: "Wait 600 seconds for host {{inventory_hostname}} to become reachable/usable"
  become: yes
  become_user: root
  remote_user: root
  ansible.builtin.wait_for_connection:
    delay: 0 # Number of seconds to wait before starting to poll.
    timeout: 600 # Maximum number of seconds to wait for.
    sleep: 5 # Number of seconds to sleep between checks.
    connect_timeout: 5 # Maximum number of seconds to wait for a connection to happen before closing and retrying.

- name: format+mount extra disks
  include: task_format_disk.yml
  vars:
    mount: "{{item.mount}}"
    device: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_{{(attached_disks.results[idx]['id'])[0:20]}}"
  when: host_disks is defined
  loop: "{{host_disks}}"
  loop_control:
    index_var: idx

