---



#There seems to be a problem with reaching the host on nic 2. It seems to work if you just ping FROM this interface

- name: "Wait 600 seconds for host {{hostname}} to finish bootup and become reachable/usable"
  remote_user: root # Ensure that we do not try to login as a user that does not exist yet
  delegate_to: "{{hostname}}"
  become: no
  wait_for_connection:
    delay: 2 # Number of seconds to wait before starting to poll.
    timeout: 600 # Maximum number of seconds to wait for.
    sleep: 2 # Number of seconds to sleep between checks.
    connect_timeout: 5 # Maximum number of seconds to wait for a connection to happen before closing and retrying.


- name: "Wait 10 seconds for host {{inventory_hostname}} to become reachable/usable"
  remote_user: root # Ensure that we do not try to login as a user that does not exist yet
  become: no
  wait_for_connection:
    delay: 0 # Number of seconds to wait before starting to poll.
    timeout: 10 # Maximum number of seconds to wait for.
    sleep: 2 # Number of seconds to sleep between checks.
    connect_timeout: 5 # Maximum number of seconds to wait for a connection to happen before closing and retrying.
  register: available_on_inventory_hostname
  ignore_errors: yes
  ignore_unreachable: yes

- name: "Activate network {{inventory_hostname}} by pinging from this host. It seems that sometimes the networks will not accept incoming
connections until they have sent some data out."
  when: available_on_inventory_hostname.failed
  remote_user: root # Ensure that we do not try to login as a user that does not exist yet
  delegate_to: "{{hostname}}"
  become: no
  shell: ping wonky.statsbiblioteket.dk -c 2

- name: "Check that host {{inventory_hostname}} is now reachable"
  remote_user: root # Ensure that we do not try to login as a user that does not exist yet
  become: no
  wait_for_connection:
    delay: 0 # Number of seconds to wait before starting to poll.
    timeout: 10 # Maximum number of seconds to wait for.
    sleep: 2 # Number of seconds to sleep between checks.
    connect_timeout: 5 # Maximum number of seconds to wait for a connection to happen before closing and retrying.
