---

#TODO lsblk to part+fs all disks
- parted:
    device: "/dev/{{device}}"
    number: 1
    flags: [ lvm ]
    state: present

- filesystem:
    fstype: xfs
    dev: "/dev/{{device}}1"

# TODO blkid
- mount:
    fstype: xfs
    src: "/dev/{{device}}1"
    path: "{{mount}}"
    state: mounted