---
- name: format and setup disk
  remote_user: root
  become: no
  block:
    - ansible.builtin.parted:
        device: "{{device}}"
        number: 1
        flags: [ lvm ]
        state: present

    - ansible.builtin.filesystem:
        fstype: xfs
        dev: "{{device}}-part1"

    - ansible.builtin.mount:
        fstype: xfs
        src: "{{device}}-part1"
        path: "{{mount}}"
        state: mounted