---

- parted:
    device: "/dev/{{device}}"
    number: 1
    flags: [ lvm ]
    state: present

- filesystem:
    fstype: ext4
    dev: "/dev/{{device}}1"

- mount:
    fstype: ext4
    src: "/dev/{{device}}1"
    path: "{{mount}}"
    state: mounted