---

- name: Create Name dir
  file:
    path: "{{hadoop_dfs_name}}"
    state: directory
    owner: "{{hdfs_user.name}}"
    group: "{{hdfs_user.name}}"
  register: hadoop_dfs_name_dir_status

- name: check if Fresh HDFS install
  set_fact:
    fresh_HDFS: '{{hadoop_dfs_name_dir_status.changed == true and hadoop_dfs_name_dir_status.diff.before.state == "absent"}}'

- include: initialize_hdfs.yml
  when: fresh_HDFS | bool or wipe_hdfs | bool


# Start both
- name: Start namenode process
  throttle: 1
  systemd:
    state: restarted
    daemon_reload: yes
    name: hdfs_namenode
    enabled: true

# Start the failover controllers
- name: Start namenode zkfc process
  throttle: 1
  systemd:
    state: restarted
    daemon_reload: yes
    name: hdfs_zkfc
    enabled: true


- name: create basic directory structure
  become: yes
  become_user: "{{hdfs_user.name}}"
  shell: | #TODO make this configurable
    set -e # Fail on anything
    source /etc/profile.d/hadoop.sh
    source /etc/profile.d/kerberos.sh

    kinit -kt {{keytab_dir}}/{{hdfs_user.name}}.headless.keytab {{hdfs_user.name}}

    hdfs dfs -mkdir -p /tmp  \
        /system \
    	/history /history/app-logs  /history/spark-history    \
    	/history/mr-history /history/mr-history/done /history/mr-history/tmp \
    	/history/timeline-server /history/timeline-server/active /history/timeline-server/done /history/timeline-server/generic-history \
    	/user;

    hdfs dfs -chmod a+rwx /tmp;

    hdfs dfs -chmod o+rx /user;

    hdfs dfs -chmod -R o+rx /history;

    hdfs dfs -chmod -R a+rwx /history/mr-history/tmp;

    hdfs dfs -chown -R {{hdfs_user.name}}:{{hadoop_group.name}} /history;

    hdfs dfs -chown {{hdfs_user.name}}:{{hadoop_group.name}} /user;

    hdfs dfs -chown -R {{yarn_user.name}}:{{hadoop_group.name}} /history/app-logs /history/timeline-server;

    hdfs dfs -chown -R {{mapreduce_user.name}}:{{hadoop_group.name}}  /history/mr-history;

    hdfs dfs -chown -R {{spark_user.name}}:{{hadoop_group.name}}  /history/spark-history;

    kdestroy
  when: primary|bool
