---

- name: install rsync so we can use ansible synchronize
  package:
    name: rsync
    state: present


- name: Create ssl dirs dir
  file:
    path: "{{ dir }}"
    state: "directory"
    mode: 0755
    owner: root
    group: "{{ hadoop_group }}"
  loop:
    - "{{ ssl_server_dir }}"
    - "{{ ssl_client_dir }}"
  loop_control:
    loop_var: "dir"


- name: "uploading ssl certs to {{inventory_hostname}}"
  throttle: 2
  delegate_to: "{{ipa_server}}"
  synchronize:
    src: "{{ item.file }}"
    dest: "{{ item.dest | default(ssl_server_dir) }}"
    archive: no
    mode: push
  loop:
    - file: "/root/ssl/{{ inventory_hostname }}-keystore.jks"
    - file: "/root/ssl/{{ inventory_hostname }}-truststore.jks"
    - file: "/root/ssl/all.jks"
    - file: "/root/ssl/http_secret"
      dest: "/etc/security/"


- name: "Setting permissions"
  file:
    path: "{{item.file}}"
    mode: "{{item.mode | default('0440')}}" #Not public
    group: "{{item.group | default(hadoop_group)}}"
    owner: "{{item.owner | default('root')}}"
  loop:
    - file: "{{ ssl_server_dir }}/{{ inventory_hostname }}-keystore.jks"
    - file: "{{ ssl_server_dir }}/{{ inventory_hostname }}-truststore.jks"
    - file: "{{ ssl_server_dir }}/all.jks"
      mode: '0444'
    - file: /etc/security/http_secret



- name: "Uploading hadoop ssl config to host"
  template:
    src: "{{ item }}"
    dest: "{{ hadoop_config_path }}/"
    mode: 0644
    owner: "root"
    group: "{{ hadoop_group }}"
  with_fileglob:
    - "templates/hadoop_conf/*"