---

- name: Create Mapreduce Paths
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ mapreduce_user.name }}"
    group: "{{ mapreduce_user.group }}"
    state: directory
    mode: 0750
  with_items:
    - "{{ mapreduce_create_path }}"

- name: install mapreduce framework in HDFS
  become: yes
  become_user: "{{hdfs_user.name}}"
  ansible.builtin.shell:
    cmd: |
    source /etc/profile.d/hadoop.sh
    source /etc/profile.d/kerberos.sh

    kinit -kt {{keytab_dir}}/{{hdfs_user.name}}.headless.keytab {{hdfs_user.name}}

    hdfs dfs -mkdir /system /system/mapreduce;
    hdfs dfs -chmod -R a+rx /system;

    mapred frameworkuploader  -target /system/mapreduce/mapreduce.tar.gz#mr-framework

- name: (Re)Start Mapreduce History Server systemd service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: mapreduce_history_server

