---


- name: Stop secondary namenode systemd service
  systemd:
    state: stopped
    daemon_reload: yes
    name: hdfs_secondary_namenode
    enabled: true
  when: wipe_hdfs | bool

- name: Wipe data
  file:
    path: "{{ hdfs_checkpoints_dir }}"
    state: absent
  when: wipe_hdfs | bool


- name: Create data dir
  file:
    path: "{{ hdfs_checkpoints_dir }}"
    state: directory
    owner: "{{ hdfs_user.name }}"
    group: "{{ hdfs_user.group }}"
    mode: 0750

- name: Format Secondary Namenode
  become: yes
  become_user: "{{ hdfs_user.name }}"
  shell:
    #TODO scan output for 'INFO namenode.SecondaryNameNode: Web server init done' rather than waiting a fixed time
    cmd:
      timeout --signal=SIGINT 10 /usr/local/bin/hadoop-invoker.sh hdfs hadoop-env.sh secondarynamenode -format > "{{ hdfs_checkpoints_dir }}/formatted"
    executable: /bin/bash
    creates: "{{ hdfs_checkpoints_dir }}/formatted"
  ignore_errors: yes


- name: (Re)Start secondary namenode systemd service
  throttle: 1
  systemd:
    state: restarted
    daemon_reload: yes
    name: hdfs_secondary_namenode
    enabled: true
