---


- name: Stop journalnode systemd service
  systemd:
    state: stopped
    daemon_reload: yes
    name: hdfs_journalnode
    enabled: true
  when: wipe_hdfs | bool

- name: Wipe journal
  file:
    path: "{{hadoop_dfs_journal}}"
    state: absent
  when: wipe_hdfs | bool

- name: Create journal dir
  file:
    path: "{{hadoop_dfs_journal}}"
    state: directory
    owner: "{{hdfs_user.name}}"
    group: "{{hdfs_user.group}}"


- name: (Re)Start journalnode systemd service
  throttle: 1
  systemd:
    state: restarted
    name: hdfs_journalnode
    enabled: true
