---
- name: Install OpenJdk.
  ansible.builtin.package: name={{ java_packages }} state=present

- name: Upload Java Home Script
  ansible.builtin.template: src=java_home.sh dest=/etc/profile.d
#
#- name: Set Java Home Script
#  ansible.builtin.shell: source /etc/profile.d/java_home.sh
