---
- name: Install OpenJdk.
  package: name={{ java_packages }} state=present

- name: Upload Java Home Script
  template:
    src: java_home.sh
    dest: /etc/profile.d
    mode: "0644"

#
#- name: Set Java Home Script
#  shell: source /etc/profile.d/java_home.sh
