---
#TODO use this instead of the direct kinit command
- name: kinit | getting a token
  ansible.builtin.command:  /usr/bin/kinit -kt {{keytab_dir}}/{{kinit_principal}}.headless.keytab {{kinit_principal}}"

- name: kinit | check token is created
  ansible.builtin.command: /usr/bin/klist
  register: result
  failed_when: "'krbtgt' not in result.stdout"

