---
- name: kinit | getting a token
  ansible.builtin.command:  /usr/bin/kinit "{{ kinit_principal | default('admin') }}"
  args:
    stdin: "{{ ipaadmin_password }}"

- name: kinit | check token is created
  ansible.builtin.command: /usr/bin/klist
  register: result
  failed_when: "'krbtgt' not in result.stdout"

