---
# General ask used by several roles

- name: "check if keytab file {{ entry.keytab_file }} exists"
  stat:
    path: "{{ entry.keytab_file }}"
  register: keytab_file

- name: "test existing keytab for  {{ entry.principal }}"
  shell: kinit -kt {{ entry.keytab_file }} {{ entry.principal}} -c test.ticket && rm test.ticket
  when: keytab_file.stat.exists == True
  register: keytab_valid

- name: "Create keytab for {{ entry.principal }}"
  when: keytab_valid.rc != 0
  block:
    - name: remove invalid keytab file
      file:
        path: "{{ entry.keytab_file }}"
        state: absent

    - name: kinit
      include_role:
        name: kinit_init

    - name: "getKeytab for {{ entry.principal }}"
      shell: ipa-getkeytab --server={{ipa_server}} --principal={{ entry.principal}} --keytab={{ entry.keytab_file }}
      args:
        creates: "{{ entry.keytab_file }}"

    - name: kdestroy
      include_role:
        name: kinit_destroy


- name: "set permissions for {{ entry.keytab_file }}"
  file:
    owner: "{{ entry.owner}}"
    group: "{{ entry.group }}"
    mode: "{{ entry.file_permissions }}"
    path: "{{ entry.keytab_file }}"
    state: "file"
