---
# General ask used by several roles

- name: "check if keytab file {{ entry.keytab_file }} exists"
  ansible.builtin.stat:
    path: "{{ entry.keytab_file }}"
  register: keytab_file

- name: "test existing keytab for  {{ entry.principal }}"
  shell:
    cmd: kinit -kt {{ entry.keytab_file }} {{ entry.principal }} -c test.ticket && rm test.ticket
  when: keytab_file.stat.exists == True
  register: keytab_valid
  failed_when: keytab_valid.rc >= 2
  changed_when: no

- name: "Create keytab for {{ entry.principal }}"
  when: keytab_valid is skipped or keytab_valid.rc != 0
  block:
    - name: remove invalid keytab file
      ansible.builtin.file:
        path: "{{ entry.keytab_file }}"
        state: absent

    - name: "getKeytab for {{ entry.principal }}"
      shell:
        cmd: ipa-getkeytab --server={{ ipa_server }} --principal={{ entry.principal }} --keytab={{ entry.keytab_file }}
      args:
        creates: "{{ entry.keytab_file }}"

- name: "set permissions for {{ entry.keytab_file }}"
  ansible.builtin.file:
    owner: "{{ entry.owner }}"
    group: "{{ entry.group }}"
    mode: "{{ entry.file_permissions }}"
    path: "{{ entry.keytab_file }}"
    state: "file"
