---

# Task for fdisking, formatting and mounting a disk. Usbed by playbook-baseVMs
- package:
    name: python36
    state: present

- parted:
    device: "/dev/{{device}}"
    number: 1
    flags: [ lvm ]
    state: present

- filesystem:
    fstype: ext4
    dev: "/dev/{{device}}1"

- mount:
    fstype: ext4
    src: "/dev/{{device}}1"
    path: "{{mount}}"
    state: mounted