---
- name: format and setup disk
  block:
    - name: "Parting {{ device }}"
      parted:
        device: "{{ device }}"
        number: 1
        flags: [ lvm ]
        state: present
        label: gpt
      register: parted

    - name: "print parted info"
      debug:
        var: parted

    - name: "Creating filesystem on {{ device }}"
      filesystem:
        fstype: xfs
        dev: "{{ device }}1"

    - name: "Discover UUID of new filesystem"
      shell:
        cmd: "blkid {{ device }}1 -o udev | grep ID_FS_UUID= | cut -d'=' -f2"
      register: blkid


    - name: "Mounting filesystem from {{ device }} on {{ mount }}"
      mount:
        fstype: xfs
        src: "UUID={{ blkid.stdout }}"
        path: "{{ mount }}"
        state: mounted
