---

remote_log_folder: /var/log/remote

structured_log_folder: /var/log/remote/hadoop

#
#    rsyslog_tls:
#      cacert: "/etc/ssl/ca.cert"
#      cert: "/etc/ssl/loghost.cert"
#      key: "/etc/ssl/private/loghost.pem"

# properties from https://rsyslog.readthedocs.io/en/latest/configuration/properties.html
rsyslog_templates:
  - name: "fromRemote"
    string: "{{remote_log_folder}}/%syslogfacility-text%/%fromhost%-%app-name%.log"
  - name: "rfc5424Format"
    string: "<%PRI%>%PROTOCOL-VERSION% timestamp=%TIMESTAMP% hostname=%hostname% app-name=%app-name% procid=%procid% msgid=%msgid% structured_data=%STRUCTURED-DATA% msg=%msg%\\n"

rsyslog_rulesets:
  - name: "remote"
    parser: "rsyslog.rfc5424"
    script: |-4
            action(
                type="omfile"
                dynaFile="fromRemote"
                template="rfc5424Format"
            )
            stop

rsyslog_inputs:
  - module: imudp
    parameters: {}
    listeners:
      - port: "{{rsyslog_server_udp_port}}"
        ruleset: "remote"

rsyslog_outputs: [ ]
