---

# PAM
- name: Allow jupyterhub to handle login sessions
  include_tasks: "pam.yml"

- name: HBAC rules
  include_tasks: hbac.yml
#
#- name: SSL certificates
#  include_tasks: ssl.yml

# Sudorules
- name: "jupyterhub Sudo rules"
  include_tasks: sudo.yml

# Install
- name: Install jupyterhub
  include_tasks: install.yml


# Config
- name: Install jupyterhub config
  include_tasks: config.yml

- name: install pyspark kernel
  include_tasks: pyspark.yml

- name: Jupyterhub Extensions
  include_tasks: extensions.yml

# Start
- name: (Re)Start Jupyterhub systemd service
  ansible.builtin.systemd:
    state: restarted
    name: jupyterhub
    enabled: true
    daemon_reload: yes

