- name: setup PAM
  copy:
    backup: yes
    src: /etc/pam.d/login
    dest: "/etc/pam.d/{{ jupyterhub_user.name }}"
    remote_src: yes

- name: Install systemd login permissions for jupyter
  ansible.builtin.template:
    src: "templates/dbus/jupyterhub.conf"
    dest: /etc/dbus-1/system.d/
    mode: 0644
    owner: "root"
    group: "root"
  register: dbus

- name: Restart systemd
  when: dbus.changed
  ansible.builtin.systemd:
    state: restarted
    name: "{{ item }}"
  loop:
    - dbus
    - systemd-logind

#  https://github.com/freeipa/ansible-freeipa/blob/master/README-hbacsvc.md
- name: "Projects HBAC service definitions"
  delegate_to: "{{ groups['hostgroup_ipaserver'] | first }}"
  run_once: true
  freeipa.ansible_freeipa.ipahbacsvc:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ jupyterhub_user.name }}" #Name should match name in /etc/pam.d/ (jupyterhub)
    description: "login to the {{ jupyterhub_user.name }} process"


#  https://github.com/freeipa/ansible-freeipa/blob/master/README-hbacrule.md
- name: "Jupyterhub HBAC rules"
  delegate_to: "{{ groups['hostgroup_ipaserver'] | first }}"
  run_once: true
  freeipa.ansible_freeipa.ipahbacrule:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ jupyterhub_user.name }} sudospawner"
    description: "Allow the jupyterhub sudospawner to use sudo to start a session for a user"
    host: "{{ groups['hostgroup_project_nodes'] }}"
    user: "{{ jupyterhub_user.name }}"
    hbacsvc:
      - "sudo"
      - "sudo-i"
    state: present
