- name: Create jupyter kernel directory
  file:
    path: /usr/local/share/jupyter/kernels/pyspark/
    mode: 0755
    state: directory
    owner: "root"
    group: "root"

- name: Install jupyter kernel config
  template:
    src: templates/kernels/pyspark.json
    dest: /usr/local/share/jupyter/kernels/pyspark/kernel.json
    mode: 0644
    owner: "root"
    group: "root"
