
# This file defines all the ports used by the system, for easier firewall config


ports: { # This dict maps roles names to ports
  "hdfs_namenode": [ "{{hdfs_namenode_rpc_port}}","{{hdfs_namenode_http_port}}","{{hdfs_namenode_https_port}}", "{{hdfs_zkfc_port}}" ],
  "hdfs_journalnode": [ "{{hdfs_journalnode_rpc_port}}","{{hdfs_journalnode_https_port}}","{{hdfs_journalnode_https_port}}" ],
  "hdfs_datanode": [ "{{hdfs_datanode_rpc_port}}", "{{hdfs_datanode_ipc_port}}", "{{hdfs_datanode_http_port}}", "{{hdfs_datanode_https_port}}" ],

  "yarn_timeline_server": [ "{{yarn_timelineserver_http_port}}", "{{yarn_timelineserver_https_port}}", "{{yarn_timelineserver_port2}}" ],
  "yarn_node_manager": [ "{{yarn_nodemanager_port}}", "{{mapreduce_shuffle_port}}" ],
  "yarn_resource_manager": [ "{{yarn_resourcemanager_rpc_port}}","{{yarn_resourcemanager_scheduler_port}}","{{yarn_resourcemanager_tracker_port}}","{{yarn_resourcemanager_admin_port}}","{{yarn_resourcemanager_http_port}}","{{yarn_resourcemanager_https_port}}" ],

  "mapreduce_history_server": [ "{{mapreduce_history_server_rpc_port}}","{{mapreduce_history_server_admin_port}}","{{mapreduce_history_server_http_port}}","{{mapreduce_history_server_https_port}}" ],

  "spark_history_server": [ "{{spark_history_server_http_port}}","{{spark_history_server_https_port}}" ],

  "zookeeper_server": [ "{{zookeeper_port}}", "{{zookeeper_leader_election_port}}", "{{zookeeper_follower_port}}" ],

  "hadoop":[] # This ensures firewall is started for all hadoop nodes
}

zookeeper_port: 2181
zookeeper_leader_election_port: 3888
zookeeper_follower_port: 2888


# HDFS
hdfs_namenode_rpc_port: 8020
hdfs_namenode_http_port: 9870
hdfs_namenode_https_port: 9871

hdfs_zkfc_port: 8019

hdfs_secondarynamenode_http_port: 9868
hdfs_secondarynamenode_https_port: 9869

hdfs_namenode_backup_rpc_port: 50100
hdfs_namenode_backup_http_port: 50105

hdfs_journalnode_http_port: 8480
hdfs_journalnode_https_port: 8481
hdfs_journalnode_rpc_port: 8485

hdfs_datanode_https_port: 9865
hdfs_datanode_rpc_port: 9866
hdfs_datanode_ipc_port: 9867
hdfs_datanode_http_port: 50475

hdfs_nfs_server_port: 2049
hdfs_nfs_mountd_port: 4242


yarn_timelineserver_http_port: 8188
yarn_timelineserver_https_port: 8190
yarn_timelineserver_port2: 10200

yarn_nodemanager_port: 45454

yarn_resourcemanager_rpc_port: 8050
yarn_resourcemanager_scheduler_port: 8030
yarn_resourcemanager_tracker_port: 8025
yarn_resourcemanager_admin_port: 8033
yarn_resourcemanager_http_port: 8088
yarn_resourcemanager_https_port: 8090

mapreduce_history_server_rpc_port: 10020
mapreduce_history_server_admin_port: 10033
mapreduce_history_server_http_port: 19888
mapreduce_history_server_https_port: 19890

mapreduce_shuffle_port: 13562


spark_history_server_https_port: 18480
spark_history_server_http_port: 18080
spark_ui_http_port: ""