
# This file defines all the ports used by the system, for easier firewall config



# ZooKeeper
default_zookeeper_port: 2181
default_zookeeper_leader_election_port: 3888
default_zookeeper_follower_port: 2888


# HDFS
default_hdfs_namenode_rpc_port: 8020
default_hdfs_namenode_http_port: 9870
default_hdfs_namenode_https_port: 9871

default_hdfs_zkfc_port: 8019

default_hdfs_secondarynamenode_http_port: 9868
default_hdfs_secondarynamenode_https_port: 9869

default_hdfs_namenode_backup_rpc_port: 50100
default_hdfs_namenode_backup_http_port: 50105

default_hdfs_journalnode_http_port: 8480
default_hdfs_journalnode_https_port: 8481
default_hdfs_journalnode_rpc_port: 8485

default_hdfs_datanode_https_port: 9865
default_hdfs_datanode_rpc_port: 9866
default_hdfs_datanode_ipc_port: 9867
default_hdfs_datanode_http_port: 50475

default_hdfs_nfs_server_port: 2049
default_hdfs_nfs_mountd_port: 4242


default_yarn_timelineserver_http_port: 8188
default_yarn_timelineserver_https_port: 8190
default_yarn_timelineserver_port2: 10200

default_yarn_nodemanager_port: 45454

default_yarn_resourcemanager_rpc_port: 8050
default_yarn_resourcemanager_scheduler_port: 8030
default_yarn_resourcemanager_tracker_port: 8025
default_yarn_resourcemanager_admin_port: 8033
default_yarn_resourcemanager_http_port: 8088
default_yarn_resourcemanager_https_port: 8090

default_mapreduce_history_server_rpc_port: 10020
default_mapreduce_history_server_admin_port: 10033
default_mapreduce_history_server_http_port: 19888
default_mapreduce_history_server_https_port: 19890

default_mapreduce_shuffle_port: 13562

default_mapreduce_am_portrange: "50000-50200"

default_spark_history_server_https_port: 18480
default_spark_history_server_http_port: 18080

default_spark_portrange_width: 50

default_spark_ui_http_port: 4400
default_spark_ui_http_portrange: "{{spark_ui_http_port}}-{{spark_ui_http_port|int+spark_portrange_width|int}}"

default_spark_driver_http_port: 12000
default_spark_driver_http_portrange: "{{spark_driver_http_port}}-{{spark_driver_http_port|int+spark_portrange_width|int}}"

default_spark_blockmanager_http_port: 12500
default_spark_blockmanager_http_portrange: "{{spark_blockmanager_http_port}}-{{spark_blockmanager_http_port|int+spark_portrange_width|int}}"

default_rstudio_server_http_port: 8787


#This reference the ports above so it must come after, due to the way that default_values work
default_ports_per_role: { # This dict maps roles names to ports
  "hdfs_namenode": [ "{{hdfs_namenode_rpc_port}}","{{hdfs_namenode_http_port}}","{{hdfs_namenode_https_port}}", "{{hdfs_zkfc_port}}" ],
  "hdfs_journalnode": [ "{{hdfs_journalnode_rpc_port}}","{{hdfs_journalnode_https_port}}","{{hdfs_journalnode_https_port}}" ],
  "hdfs_datanode": [ "{{hdfs_datanode_rpc_port}}", "{{hdfs_datanode_ipc_port}}", "{{hdfs_datanode_http_port}}", "{{hdfs_datanode_https_port}}" ],

  "yarn_timeline_server": [ "{{yarn_timelineserver_http_port}}", "{{yarn_timelineserver_https_port}}", "{{yarn_timelineserver_port2}}" ],
  "yarn_node_manager": [ "{{yarn_nodemanager_port}}",
                         "{{mapreduce_shuffle_port}}",
                         "{{mapreduce_am_portrange}}",
                         "{{spark_ui_http_portrange}}",
                         "{{spark_driver_http_portrange}}",
                         "{{spark_blockmanager_http_portrange}}"
  ],
  "yarn_resource_manager": [ "{{yarn_resourcemanager_rpc_port}}",
                             "{{yarn_resourcemanager_scheduler_port}}",
                             "{{yarn_resourcemanager_tracker_port}}",
                             "{{yarn_resourcemanager_admin_port}}",
                             "{{yarn_resourcemanager_http_port}}",
                             "{{yarn_resourcemanager_https_port}}" ],

  "mapreduce_history_server": [ "{{mapreduce_history_server_rpc_port}}","{{mapreduce_history_server_admin_port}}","{{mapreduce_history_server_http_port}}","{{mapreduce_history_server_https_port}}" ],

  "spark_history_server": [ "{{spark_history_server_http_port}}","{{spark_history_server_https_port}}" ],

  "zookeeper_server": [ "{{zookeeper_port}}", "{{zookeeper_leader_election_port}}", "{{zookeeper_follower_port}}" ],


  "spark_client": [ "{{spark_ui_http_portrange}}",
                    "{{spark_driver_http_portrange}}",
                    "{{spark_blockmanager_http_portrange}}" ],

  "rstudio_server": [ "{{rstudio_server_http_port}}" ],

  "hadoop": [ ] # This ensures that the firewall is started for all hadoop nodes

}