# You will make one inventory file per cluster. So all cluster-specific settings should go into this file

# These are the magical hostgroups that are automagically bound to roles and behaviours
# hostgroup_VMs: Machines to auto-create in ovirt
# hostgroup_ipaserver: the FreeIPA server to register all hosts to
# hostgroup_ipaclients: The list of hosts to setup as ipa clients
# hostgroup_rsyslog_server: The rsyslog server forward all log messages to
# hostgroup_zabbix_nodes: The list of hosts to setup zabbix agent on
# hostgroup_hadoop_nodes: = role hadoop, role zookeeper, role spark
# hostgroup_hdfs_namenodes: = role hadoop_hdfs_namenode
# hostgroup_hdfs_journalnodes: = role hadoop_hdfs_journalnode
# hostgroup_hdfs_datanodes: = role hadoop_hdfs_datanode
# hostgroup_zookeeper_servers: = role zookeeper_server
# hostgroup_yarn_resource_managers: = role hadoop_yarn_resource_manager
# hostgroup_yarn_node_managers: = role hadoop_yarn_node_manager
# hostgroup_yarn_timeline_servers: = role hadoop_yarn_timeline_server
# hostgroup_mapreduce_history_servers: = role hadoop_mapreduce_history_server
# hostgroup_spark_history_servers: = role spark_history_server
# hostgroup_project_nodes: = role spark_client, role rstudio_server

hostgroup_all:
  children:
    hostgroup_ansible_host:
      hosts:
        localhost:

    hostgroup_ipaserver: # Singular form as there can be only one here
      hosts:
        ipa.askov.net:

    hostgroup_ipaclients:
      children: #Mark all hadoop nodes as ipa-clients
        hostgroup_hadoop_nodes:

    hostgroup_rsyslog_server:
      hosts:
        ipa.askov.net:

    hostgroup_with_datamounts:
      children:
        hostgroup_hdfs_datanodes:

    hostgroup_hadoop_nodes:
      children:

        hostgroup_project_nodes:
          hosts:
            projects.askov.net:
          children:
            hostgroup_jupyter_nodes:
              hosts:
                projects.askov.net:

            hostgroup_rstudio_nodes:
              hosts:
                projects.askov.net:

        hostgroup_hdfs:
          children:
            hostgroup_hdfs_namenodes:
              hosts:
                hadoop.askov.net:

            hostgroup_hdfs_secondary_namenodes:
              hosts:
                hadoop.askov.net:

            hostgroup_hdfs_journalnodes:
              hosts:

            hostgroup_hdfs_backupnodes:
              hosts:

            hostgroup_hdfs_datanodes:
              hosts:
                data[1:3].askov.net:
                  mounts:
                    - mount: /data/vdb1
                      device: /dev/vdb
                  hdfs_data_dirs:
                    - /data/vdb1/hdfs

        hostgroup_zookeeper_servers:
          hosts:
            hadoop.askov.net:

        hostgroup_yarn:
          hosts:
          vars:
            yarn_scheduler_max_memory: 8192
            yarn_scheduler_max_cpu_cores: 8
          children:
            hostgroup_yarn_resource_managers:
              hosts:
                hadoop.askov.net:

            hostgroup_yarn_node_managers:
              vars:
                yarn_nodemanager_available_cpu_cores: 4
                yarn_nodemanager_available_memory: 4096
                yarn_data_dirs:
                  - /data/vdb1/yarn
              hosts:
                data[1:3].askov.net:

            hostgroup_yarn_timeline_servers:
              hosts:
                hadoop.askov.net:

        hostgroup_mapreduce:
          hosts:
          children:
            hostgroup_mapreduce_history_servers:
              hosts: # There can be only one here
                hadoop.askov.net:

        hostgroup_spark:
          hosts:
          children:
            hostgroup_spark_history_servers:
              hosts: # There can be only one here
                hadoop.askov.net:

