- ansible.builtin.set_fact: # set_fact to register this variable
    kerberos_conf: >
      {%- set temp_list = [] -%}
      {%- for host in groups['hostgroup_all'] -%}
      {%- for service in keytab_services if (service.hostgroup in hostvars[host]['group_names'] or service.hostgroup == 'hostgroup_all') -%}
      {%- set temp_dic = {} -%}
      {%- set _= temp_dic.update({'host': hostvars[host]['ansible_fqdn'] }) -%}
      {%- set _= temp_dic.update({'type': 'SERVICE' }) -%}
      {%- set _= temp_dic.update({'principal': ( service.service | default(service.name))+'/'+hostvars[host]['ansible_fqdn']+'@'+ipaserver_realm }) -%}
      {%- set _= temp_dic.update({'keytab_file': keytab_dir+'/'+service.name+'.service.keytab' }) -%}
      {%- set _= temp_dic.update({'owner': service.owner }) -%}
      {%- set _= temp_dic.update({'group': service.group }) -%}
      {%- set _= temp_dic.update({'file_permissions': service.permissions | default(keytab_permissions) }) -%}
      {%- set _= temp_list.append(temp_dic) -%}
      {%- endfor %}
      {%- endfor %}
      {%- for host in groups['hostgroup_all'] -%}
      {%- for user in keytab_users if (user.hostgroup in hostvars[host]['group_names'] or user.hostgroup == 'hostgroup_all') -%}
      {%- set temp_dic = {} -%}
      {%- set _= temp_dic.update({'host': hostvars[host]['ansible_fqdn'] }) -%}
      {%- set _= temp_dic.update({'type': 'USER' }) -%}
      {%- set _= temp_dic.update({'principal': user.name+'@'+ipaserver_realm }) -%}
      {%- set _= temp_dic.update({'keytab_file': keytab_dir+'/'+user.name+'.headless.keytab' }) -%}
      {%- set _= temp_dic.update({'owner': user.owner }) -%}
      {%- set _= temp_dic.update({'group': user.group }) -%}
      {%- set _= temp_dic.update({'file_permissions': entry.permissions | default(keytab_permissions) }) -%}
      {%- set _= temp_list.append(temp_dic) -%}
      {%- endfor %}
      {%- endfor %}
      {{ - temp_list - }}
