---

- name: Create Name dir
  ansible.builtin.file:
    path: "{{hadoop_dfs_name}}"
    state: directory
    owner: "{{hdfs_user.name}}"
    group: "{{hdfs_user.name}}"
  register: hadoop_dfs_name_dir_status

- name: check if Fresh HDFS install
  ansible.builtin.set_fact:
    fresh_HDFS: '{{hadoop_dfs_name_dir_status.changed == true and hadoop_dfs_name_dir_status.diff.before.state == "absent"}}'

- include: initialize_ha_hdfs.yml
  when: hdfs_high_availability | bool and (fresh_HDFS | bool or wipe_hdfs | bool)


- include: initialize_normal_hdfs.yml
  when: not hdfs_high_availability | bool and (fresh_HDFS | bool or wipe_hdfs | bool)


# Start both
- name: (Re)Start namenode systemd service
  throttle: 1
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: hdfs_namenode
    enabled: true

# Start the failover controllers
- name: (Re)Start namenode zkfc systemd service
  when: hdfs_high_availability
  throttle: 1
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: hdfs_zkfc
    enabled: true

