---

projects_ipa: "{{lookup('vars', *(projects | map(attribute='name'))) | map(attribute='project_ipa') | list }}"

common_usergroups: []

shell: /bin/bash

hdfs_delegation_host:  "{{ groups['hdfs'] | first }}"