---

zookeeper_version: "3.6.2"
zookeeper_download: "https://mirrors.dotsrc.org/apache/zookeeper/zookeeper-{{zookeeper_version}}/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz"

zookeeper_path: "/usr/local/zookeeper"

zookeeper_home: "{{zookeeper_path}}/apache-zookeeper-{{zookeeper_version}}-bin"

current_zookeeper_home: "{{ zookeeper_path }}/current"

zookeeper_daemon_logger: "DEBUG, CONSOLE, DAILYROLLINGFILE"


zookeeper_log_path: "/var/log/zookeeper/"
zookeeper_pid_dir: "/var/run/zookeeper/"

zookeeper_config_path: "/etc/zookeeper/conf/"


zookeeper_data_dir: "/zookeeper-data/"

zookeeper_create_path:
  - "{{zookeeper_data_dir}}"
  - "{{zookeeper_config_path}}"
  - "{{zookeeper_log_path}}"
  - "{{zookeeper_pid_dir}}"
  - "{{zookeeper_path}}"



