---
- name: install firewalld
  ansible.builtin.package:
    state: present
    name:
      - firewalld
      - python3-firewall

- name: firewalld is running
  ansible.builtin.systemd:
    state: started
    service: firewalld

- name: "Open Firewall for group {{item}}"
  include: open_firewall.yml rolename={{item}}
  loop: "{{ ansible_role_names }}"

