---
# Remove open ports with a command like
# ansible -i  hosts/narchive-test/ all -u root -a "bash -c \"firewall-cmd --list-ports | tr ' ' '\n' | xargs -r -Iæ firewall-cmd --permanent --remove-port='æ'\""
# ansible -i  hosts/narchive-test/ all -u root -a "bash -c \"firewall-cmd --list-rich-rules | xargs -r -Iæ firewall-cmd --permanent --remove-rich-rule='æ'\""
#  ansible -i hosts/YAK2-abstract/ -i  hosts/YAK2-ha/ all -u root -a "bash -c \"firewall-cmd --list-ports | tr ' ' '\n' | xargs -r -Iæ firewall-cmd --permanent --remove-port='æ'\""
#  ansible -i hosts/YAK2-abstract/ -i  hosts/YAK2-ha/ all -u root -a "bash -c \"firewall-cmd --list-rich-rules | xargs -r -Iæ firewall-cmd --permanent --remove-rich-rule='æ'\""
- name: install firewalld
  package:
    state: present
    name:
      - firewalld
      - python3-firewall

- name: Upload Service config files
  template:
    src: "{{ item }}"
    dest: "/etc/firewalld/services/"
    mode: 0644
    owner: "root"
    group: "root"
  with_fileglob:
    - "templates/services/*"


- name: firewalld is running
  systemd:
    state: started
    service: firewalld
    enabled: yes


- name: Ensure the new firewall services are loaded
  systemd:
    state: reloaded
    service: firewalld


- name: "Open Firewall for group {{ ansible_role_names }}"
  include: open_firewall.yml rolename={{ item }}
  loop: "{{ ansible_role_names }}"

