---
# Remove open ports with a command like
# ansible -i  hosts/narchive-test/ all -u root -a "bash -c \"firewall-cmd --list-ports | tr ' ' '\n' | xargs -r -Iæ firewall-cmd --permanent --remove-port='æ'\""
# ansible -i  hosts/narchive-test/ all -u root -a "bash -c \"firewall-cmd --list-rich-rules | xargs -r -Iæ firewall-cmd --permanent --remove-rich-rule='æ'\""
- name: install firewalld
  ansible.builtin.package:
    state: present
    name:
      - firewalld
      - python3-firewall

- name: Upload Service config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/firewalld/services/"
    mode: 0644
    owner: "root"
    group: "root"
  with_fileglob:
    - "templates/services/*"


- name: firewalld is running
  ansible.builtin.systemd:
    state: started
    service: firewalld
    enabled: yes


- name: Ensure the new firewall services are loaded
  ansible.builtin.systemd:
    state: reloaded
    service: firewalld


- name: "Open Firewall for group {{item}}"
  include: open_firewall.yml rolename={{item}}
  loop: "{{ ansible_role_names }}"

