---
- name: "Ensure firewall is started"
  systemd:
    state: started
    name: firewalld
    daemon_reload: yes
  when: ports[rolename] is defined


- name: "Open Firewall ports for {{rolename}}"
  firewalld:
    port: '{{port}}/tcp'
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  loop: "{{ports_per_role[rolename]}}"
  when: ports_per_role[rolename] is defined
  loop_control:
    loop_var: port
