---
- name: "Open Firewall ports for {{rolename}}"
  firewalld:
    port: '{{port}}/tcp'
    permanent: yes
    state: enabled
    zone: public
    immediate: yes
    #TODO description
  loop: "{{ports_per_role[rolename]}}"
  when: ports_per_role[rolename] is defined
  loop_control:
    loop_var: port
