---
- name: "Open Firewall ports for {{rolename}}"
  ansible.posix.firewalld:
    port: '{{port.port}}/{{port.protocol | default("tcp")}}'
    permanent: yes
    state: enabled
    zone: "{{port.zone| default('public')}}"
    source: "{{port.source | default(omit)}}"
    immediate: yes
    #TODO description
  loop: "{{ports_per_role[rolename]}}"
  when: ports_per_role[rolename] is defined
  loop_control:
    loop_var: port
