---
- name: Create service keytabs dir
  file:
    owner: root
    group: "{{ hadoop_group.name }}"
    mode: 0750
    path: "{{ dir }}"
    state: "directory"
  loop: '{{ kerberos_conf | selectattr("host", "eq", ansible_fqdn) | map(attribute="keytab_file") | map("dirname") |unique| list }}'
  loop_control:
    loop_var: "dir"

- name: kinit admin
  include_tasks: kinit_admin.yml

# Service keytabs are created directly on the host that needs them, as they are host-specific
- name: Retrieving keytab for host
  include_tasks: retrieveKeytab.yml
  vars:
    entry: "{{ item }}"
  with_items: '{{ kerberos_conf | selectattr("host", "eq", ansible_fqdn) | list }}'
  #DO NOT DO THIS FOR THE IPA SERVER AS YOU MIGHT OVERWRITE SOMETHING IT USES. TODO make this into a fail: task
  # the spnego/HTTP certificate has the same principal as /var/lib/ipa/gssproxy/http.keytab and will break the server when
  #   regenerated

- name: kdestroy
  include_tasks: kdestroy.yml
