---
sealbin_user: "abr"


domain: askov.net

# If not defined, the system will use the uppercase of the domain above
# But as the IPA server apparently only handles ONE realm, we must use this realm
# IF not set at all, it might autodiscover from DNS
# _kerberos.hadoop.bitarkiv.kb.dk. 86400 IN TXT "KBHPC.KB.DK"
ipa_realm: "ASKOV.NET"

ipaclient_force_join: yes

# This is the freeipa host. Set this variable if you need to clients to contact it on another hostname
# than defined in the inventory
#ipa_server: "{{  groups['hostgroup_ipaserver'] | map('extract',hostvars, 'ansible_fqdn') | first }}"

#If you do not define this, the clients will use DNS autodiscovery where they look for
# _kerberos-master._tcp.hadoop.bitarkiv.kb.dk. 86400 IN SRV 0 100 88 kbhpc-fipa-001.kbhpc.kb.dk.
# _kerberos-master._udp.hadoop.bitarkiv.kb.dk. 86400 IN SRV 0 100 88 kbhpc-fipa-001.kbhpc.kb.dk.
# _kerberos._tcp.hadoop.bitarkiv.kb.dk. 86400 IN SRV 0 100 88 kbhpc-fipa-001.kbhpc.kb.dk.
# _kerberos._udp.hadoop.bitarkiv.kb.dk. 86400 IN SRV 0 100 88 kbhpc-fipa-001.kbhpc.kb.dk.
# _kpasswd._tcp.hadoop.bitarkiv.kb.dk. 86400 IN SRV 0 100 464 kbhpc-fipa-001.kbhpc.kb.dk.
# _kpasswd._udp.hadoop.bitarkiv.kb.dk. 86400 IN SRV 0 100 464 kbhpc-fipa-001.kbhpc.kb.dk.
# _ldap._tcp.hadoop.bitarkiv.kb.dk. 86400 IN SRV 0 100 389 kbhpc-fipa-001.kbhpc.kb.dk.
ipaclient_servers: ["ipa.askov.net"]
ipaclient_no_dns_lookup: yes

#Use localhomes for system users
use_nfs_syshomes: no

# Use localhomes for project users
use_autofs_homes: no

#Autocreate home dirs upon login
ipaclient_mkhomedir: yes

ipaclient_ntp_pool: pool.ntp.org

ipa_hostgroup: hadoop

user_prefix: ""

#See https://sbprojects.statsbiblioteket.dk/display/HPC/Users
cluster_id_prefix: "12"


ipaadmin_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31373638633739316236356362666631376230346537313134356634363838313835333363303034
  3931323161633839316363623335343331306463613663650a616438633836656464623564303939
  36323665376638613933663761633237326530313266333361653432353434363963346136643836
  6138643161373930320a306230386233623537633933383637376165343664663938633737386361
  31393438613639643366643461353131303730643137613930626561633961326462