---

- name: zookeeper_id
  template: src=myid dest={{zookeeper_data_dir}}/myid mode=0644 owner="root" group="root"

- name: Start zookeeper server
  systemd:
    state: started
    daemon_reload: yes
    name: zookeeper
    enabled: true
