---

- name: "Install packages"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-server
    - python3-psycopg2 # For ansible database creation steps in setup_postgresql_db.yml

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "Start and enable services"
  systemd:
    name: postgresql
    state: started
    enabled: yes
