---

- name: "install postgres"
  include: install_postgresql.yml

- name: "setup postgres"
  include: setup_postgresql_db.yml


- name: Force OS Redhat when on Springdale
  when: ansible_os_family == 'Springdale'
  set_fact:
    zabbix_agent_os_family: RedHat

# https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_PROXY_ROLE.md
- name: zetup zabbix proxies
  include_role:
    name: community.zabbix.zabbix_proxy

- name: Restart firewalld to pick up changes
  when: zabbix_agent_firewalld_enable | default(False) | bool
  systemd:
    service: firewalld
    state: restarted

- name: Enable zabbix selinux module
  when:
    - zabbix_custom_selinux
    - ansible_selinux.status != 'disabled'
  import_role:
    name: zabbix_selinux


- name: Fix selinux permissions
  when:
    - ansible_selinux.status != 'disabled'
    - ansible_selinux.mode == 'enforcing'
  command: "restorecon -R -v /var/lib/zabbix"


- name: (Re)Start zabbix proxy service
  systemd:
    service: zabbix-proxy
    state: restarted
    enabled: yes
