---


- name: Default Sudo rules
  ipasudorule:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: defaults
    hostcategory: all
    usercategory: all
    sudooption:
      - '!requiretty'
      - '!env_reset'
      - 'env_delete-=PATH'

- name: "{{subadmins_group}} Sudo rules"
  ipasudorule:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{subadmins_group}}"
    hostcategory: all
    cmdcategory: all
    runasusercategory: all
    runasgroupcategory: all
    sudooption:
      - '!requiretty'
      - '!authenticate'
    group:
      - "{{subadmins_group}}"
      - "{{ipa_admin_group}}"

