---


- name: Default Sudo rules
  freeipa.ansible_freeipa.ipasudorule:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: defaults
    hostcategory: all
    usercategory: all
    sudooption:
      - '!requiretty'
      - '!env_reset'
      - 'env_delete-=PATH'

- name: "{{ subadmins_group.name }} Sudo rules"
  freeipa.ansible_freeipa.ipasudorule:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ subadmins_group.name }}"
    hostgroup:
      - "{{ ipa_hostgroup | default(domain) }}"
    cmdcategory: all
    runasusercategory: all
    runasgroupcategory: all
    sudooption:
      - '!requiretty'
      - '!authenticate'
    group:
      - "{{ subadmins_group.name }}"
      - "{{ ipa_admin_user.group }}"

