---

default_project_file_dir: hosts/YAK2-abstract/group_vars/hostgroup_all/projects
# Append new project names here, to automatically load ./projects/<name>.yml

projects:
  - name: subadmins_project
#    file: hosts/YAK2/group_vars/hostgroup_all/projects/subadmins_project.yml
  - name: p001
#    file: hosts/YAK2/group_vars/hostgroup_all/projects/p001.yml
  - name: p002
#    file: hosts/YAK2/group_vars/hostgroup_all/projects/p002.yml
  - name: p003

default_queue_mapping: "g:{{users_group.name}}:default"
