---

- name: Create system user keytabs dir
  file:
    owner: root
    group: "{{ hadoop_group.name }}"
    mode: 0750
    path: "{{ dir }}"
    state: "directory"
  loop: '{{ kerberos_conf | selectattr("type", "eq", "USER") | map(attribute="keytab_file") | map("dirname") |unique| list}}'
  loop_control:
    loop_var: "dir"



- name: "uploading headless keytabs to hosts"
  throttle: 2
  delegate_to: "{{ipa_server}}"
  remote_user: root
  synchronize:
    src: "{{ item }}"
    dest: "{{keytab_dir}}"
    mode: push
  loop: '{{ kerberos_conf | selectattr("type", "eq", "USER") | map(attribute="keytab_file") |unique| list}}'

