---

- name: Create system user keytabs dir
  file:
    owner: root
    group: "{{ hadoop_group }}"
    mode: 0750
    path: "{{ dir }}"
    state: "directory"
  loop: '{{ kerberos_conf | selectattr("type", "eq", "USER") | map(attribute="keytab_file") | map("dirname") |unique| list}}'
  loop_control:
    loop_var: "dir"



# System user keytabs are created on the ipa server and distributed below
- name: Retrieving keytab for user
  include_tasks: retrieveKeytab.yml
  vars:
    entry: "{{item}}"
  with_items: '{{ kerberos_conf | selectattr("type", "eq", "USER") | list}}'
  when: create_system_user_keytabs


- name: fetching keytabs for headless users to localhost
  fetch:
    src: "{{ item }}"
    dest: keytabs/
    flat: true
  loop: '{{ kerberos_conf | selectattr("type", "eq", "USER") | map(attribute="keytab_file") | unique| list}}'
  when: create_system_user_keytabs

- name: "uploading headless keytabs to {{ inventory_hostname }}"
  copy:
    src: "{{ item }}"
    dest: "{{keytab_dir}}"
  with_fileglob:
    - "./keytabs/*"
  when: upload_system_user_keytabs

