---

- name: "Create system user keytabs dir"
  file:
    owner: root
    group: "{{ hadoop_group.name }}"
    mode: 0750
    path: "{{ dir }}"
    state: "directory"
  loop: '{{ kerberos_conf | selectattr("type", "eq", "USER") | map(attribute="keytab_file") | map("dirname") |unique| list }}'
  loop_control:
    loop_var: "dir"




- name: "uploading headless keytabs to hosts"
  throttle: 2
  copy:
    src: "{{ keytab.keytab_file }}"
    dest: "{{ keytab_dir }}"
    mode: "{{ keytab.file_permissions }}"
    owner: "{{ keytab.owner }}"
    group: " {{ keytab.group }}"
  loop: '{{ kerberos_conf | selectattr("type", "eq", "USER") | unique| list }}'
  loop_control:
    loop_var: "keytab"


