---

- name: Create system user keytabs dir
  file:
    owner: root
    group: "{{ hadoop_group.name }}"
    mode: 0750
    path: "{{ dir }}"
    state: "directory"
  loop: '{{ kerberos_conf | selectattr("type", "eq", "USER") | map(attribute="keytab_file") | map("dirname") |unique| list }}'
  loop_control:
    loop_var: "dir"


- name: Retrieving keytab for user
  delegate_to: localhost
  become: no
  remote_user: root
  block:
    - name: kinit_admin
      include_tasks: kinit_admin.yml

    # System user keytabs are created on the ipa server and distributed below
    - name: Retrieving keytab for user
      include_tasks: retrieveKeytab.yml
      vars:
        entry: "{{ item }}"
      with_items: '{{ kerberos_conf | selectattr("type", "eq", "USER") | list }}'

    - name: kdestroy
      include_tasks: kdestroy.yml
