---
#
#- name: Create system user keytabs dir
#  file:
#    owner: root
#    group: "{{ hadoop_group.name }}"
#    mode: 0750
#    path: "{{ dir }}"
#    state: "directory"
#  loop: '{{ kerberos_conf | selectattr("type", "eq", "USER") | map(attribute="keytab_file") | map("dirname") |unique| list }}'
#  loop_control:
#    loop_var: "dir"


- name: Retrieving keytab for user
  block:
    - name: kinit_admin
      include_tasks: kinit_admin.yml

    # System user keytabs are created on the ansible server and distributed below
    - name: Retrieving keytab for user
      include_tasks: retrieveUserKeytab.yml
      vars:
        entry: "{{ item }}"
        output_dir: "{{ temp_keytab_dir }}"
      with_items: '{{ kerberos_conf | selectattr("type", "eq", "USER") | list }}'

    - name: kdestroy
      include_tasks: kdestroy.yml
