---

- name: Create default user groups
  loop: "{{default_user_groups}}"
  freeipa.ansible_freeipa.ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    description: "{{item.description}}"


- name: "Projects setup"
  loop: "{{projects_ipa}}" # TODO this fails if there is only one project defined. How to fix?
  loop_control:
    loop_var: group
  include_tasks: createGroupAndUsers.yml


- name: Create HBAC service group
  throttle: 1
  freeipa.ansible_freeipa.ipahbacsvcgroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "user-session"
    hbacsvc: "{{hbac_services | reject('eq',omit)}}"

#  https://github.com/freeipa/ansible-freeipa/blob/master/README-hbacrule.md
- name: "Projects HBAC rules"
  run_once: true
  loop: "{{projects_ipa}}"
  loop_control:
    loop_var: group
  when: group.project_host is defined
  freeipa.ansible_freeipa.ipahbacrule:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{group.name}} allowed on {{group.project_host}}"
    host: "{{group.project_host}}"
    group: "{{group.name}}"
    hbacsvcgroup: "user-session"
    state: present

#  https://github.com/freeipa/ansible-freeipa/blob/master/README-hbacrule.md
- name: "Subadmin HBAC rules"
  freeipa.ansible_freeipa.ipahbacrule:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{subadmins_project.project_ipa.name}} allowed on all"
    group: "{{subadmins_project.project_ipa.name}}"
    hostcategory: "all"
    hbacsvcgroup: "user-session"
    state: present