
- name: Create HBAC service group
  freeipa.ansible_freeipa.ipahbacsvcgroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{user_prefix}}user-session"
    hbacsvc: "{{hbac_services | reject('eq',omit)}}"

#  https://github.com/freeipa/ansible-freeipa/blob/master/README-hbacrule.md
- name: "Projects HBAC rules"
  loop: "{{projects_ipa}}"
  loop_control:
    loop_var: group
  when: group.project_host is defined
  freeipa.ansible_freeipa.ipahbacrule:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{group.name}} allowed on {{group.project_host}}"
    host: "{{group.project_host}}"
    group: "{{group.name}}"
    hbacsvcgroup:
      - "{{user_prefix}}user-session"
    state: present

#  https://github.com/freeipa/ansible-freeipa/blob/master/README-hbacrule.md
- name: "Subadmin HBAC rules"
  freeipa.ansible_freeipa.ipahbacrule:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{subadmins_project.project_ipa.name}} allowed on all"
    group: "{{subadmins_project.project_ipa.name}}"
    hostcategory: "all"
    hbacsvcgroup:
      - "{{user_prefix}}user-session"
      - "Sudo"
    state: present