---
- name: analyze - Merge files list
  set_fact:
    _log4shell_files: "{{ ( _log4shell_grep_files | default([]) ) +  ( _log4shell_find_files | default([]) ) + ( _log4shell_lsof_files | default([]) )  | list | unique }}"
...
