---

- name: Create common dirs
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "root"
    group: "{{ spark_user.group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ spark_log_dir }}"
    - "{{ spark_tmp }}"



- name: ensure spark directory exists
  ansible.builtin.file:
    path: "{{ spark_path }}"
    state: directory


- ansible.builtin.debug:
    msg: "Downloading Spark from {{spark_download}}"


- name: Unzip Spark
  ansible.builtin.unarchive:
    src: "{{ spark_download }}"
    dest: "{{ spark_path }}"
    remote_src: yes
    creates: "{{ spark_home }}"
    group: "{{ spark_user.group }}"
    owner: "root"

- name: Replace spark log4j library with hadoop log4j library to avoid warnings
  block:
    - name: "Link {{spark_home}} to {{current_spark_home}}"
      ansible.builtin.file:
        src: "{{spark_home}}"
        dest: "{{current_spark_home}}"
        state: link

    - name: Ansible delete file wildcard
      ansible.builtin.find:
        paths: "{{current_spark_home}}/jars/"
        patterns: "slf4j-log4j12-*.jar"
      register: wildcard_files_to_delete

    - name: Ansible remove file wildcard
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ wildcard_files_to_delete.files }}"

    - name: Ansible link file wildcard
      ansible.builtin.find:
        paths: "{{current_hadoop_home}}/share/hadoop/common/lib/"
        patterns: "slf4j-log4j12-*.jar"
      register: wildcard_files_to_link

    - name: Ansible link file wildcard
      ansible.builtin.file:
        src: "{{ item.path }}"
        force: yes
        dest: "{{current_spark_home}}/jars/{{item.path | basename}}"
        state: link
      with_items: "{{ wildcard_files_to_link.files }}"



- name: Upload spark config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ spark_config_path }}/"
    mode: 0644
    owner: "root"
    group: "{{ spark_user.group }}"
  with_fileglob:
    - "templates/spark_conf/*"


- name: remove {{ spark_home }}/conf
  ansible.builtin.file:
    path: "{{ spark_home }}/conf"
    state: absent
- name: symlink {{ spark_home }}/conf to {{ spark_config_path }}
  ansible.builtin.file:
    src: "{{ spark_config_path }}"
    dest:  "{{ spark_home }}/conf"
    owner: root
    group: "{{ spark_user.group }}"
    state: link
    force: true


- name: Upload Spark profile files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/profile.d/"
    mode: 0644
    owner: "root"
    group: "{{ spark_user.group }}"
  with_fileglob:
    - "templates/profile.d/*"

