---

- name: Merge ansible host groups
  merge_vars:
    suffix_to_merge: zabbix_host_groups__to_merge
    merged_var_name: zabbix_host_groups
    expected_type: 'list'

- debug: var=zabbix_host_groups

# https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_AGENT_ROLE.md
- name: zetup zabbix agentz
  include_role:
    name: community.zabbix.zabbix_agent

# TODO is this unnessesary? Does the zabbix agent do this automatigally?
- name: Zetup Zelinux for Zabbix.
  block:
    - name: Upload Zabbix selinux modulue
      template:
        src: "zabbix_agent.te"
        dest: "."
        mode: 0644
        owner: "root"
        group: "root"


    - name: Install tools for selinux
      package:
        name: checkpolicy
        state: present

    - name: Create selinux policy module
      shell:
        cmd: checkmodule --mls -m --output zabbix_agent.mod zabbix_agent.te
        creates: zabbix_agent.mod
      # In order to build a policy package from a type enforcement file, we first have to convert it into a policy module. This is done with the checkmodule command.
      #This command will take our myapp.te file and create a myapp.mod policy module in our current working directory.

    #We can now take this policy module and compile it:
    - name: Compile selinux policy module
      shell:
        cmd: semodule_package --outfile zabbix_agent.pp --module zabbix_agent.mod
        creates:  zabbix_agent.pp
      #This command will result in a policy package called zabbix_agent.pp in our working directory.
      #
      #This generated policy package can now be loaded with the semodule command:
    - name: load selinux module package
      shell: semodule --install zabbix_agent.pp

- name: Fix selinux permissions
  command: restorecon -R -v /var/lib/zabbix

- name: Start zabbix agent service
  systemd:
    service: zabbix-agent
    state: started
    enabled: yes
