---

- name: Force OS Redhat when on Springdale
  when: ansible_os_family == 'Springdale'
  set_fact:
    zabbix_agent_os_family: RedHat



- name: Merge ansible host groups
  merge_vars:
    suffix_to_merge: zabbix_host_groups__to_merge
    merged_var_name: zabbix_host_groups
    expected_type: 'list'

- debug: var=zabbix_host_groups

# https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_AGENT_ROLE.md
- name: zetup zabbix agentz
  include_role:
    name: community.zabbix.zabbix_agent


- name: Fix selinux permissions
  when: ansible_selinux.mode == 'enforcing'
  command: "restorecon -R -v /var/lib/zabbix"


- name: (Re)Start zabbix agent service
  systemd:
    service: zabbix-agent
    state: restarted
    enabled: yes
