---

#Defaults if the relevant field have not been set

default_shortname: "{{  inventory_hostname.split('.')[0] | lower }}"
default_hostname: "{{shortname}}.{{domain}}"

default_template: "SDL8-4R-30D-MIN-TMPL"
default_memory: "4GiB"
default_cpu_sockets: 2
default_cpu_cores: 1
default_description: "{{group_names | sort | join(' ')}}"

letters: "abcdefghicklmopqrstuvwxyz" #For format to figure out the letter code of the new disk
