---
ssl_key_size: 2048

sealbin_user: "sealbin"
temp_ssl_dir: "/home/{{sealbin_user}}/ssl"

ssl_organizational_unit_name: demo
ssl_organization_name: MyOrg
ssl_locality_name: Pune
ssl_state_or_province_name: MH
ssl_country_name: IN

certificate_authority:
  private_key_file: "{{temp_ssl_dir}}/CA-private.pem"
  private_key_passphrase: "YOUR PASSWORD HERE"
  certificate_file: "{{temp_ssl_dir}}/CA.crt"
  name: "CA"


hadoop_config_path: "/etc/hadoop/conf"


#Common SSL variables
ssl_server_dir: /etc/ssl
ssl_client_dir: /etc/ssl
