---
- name: kinit | getting a token
  command:  /usr/bin/kinit "{{ kinit_principal | default('admin') }}"
  args:
    stdin: "{{ ipaadmin_password }}"
  become: no

- name: kinit | check token is created
  command: /usr/bin/klist
  register: result
  failed_when: "'krbtgt' not in result.stdout"
  become: no

