---
# Vars in here will be available as p001.*


#project_ipa controls project group and users.
project_ipa:
  name: "{{users_group.name}}"
  gid: "{{users_group.gid}}"
  # Project_host is used to set up HBAC rules
  project_host: "narchive-t-admn02.kb.dk"
  users:
    - username: "{{user_prefix}}nas-devel"
      firstname: "NetArchive Suite"
      lastname: "Application user"
      mobile: ""
      uid: "{{users_group.gid | int +1}}"
      gid: "{{users_group.gid}}"
      noprivate: yes

    - username: "{{user_prefix}}elzi-devel"
      firstname: "Eld"
      lastname: "Zierau"
      mobile: "+4591324690"
      email: "elzi@kb.dk"

    - username: "{{user_prefix}}rbkr-devel"
      firstname: "Rasmus"
      lastname: "Bohl Kristensen"
      mobile: "+4551671363"
      email: "rbkr@kb.dk"

    - username: "{{user_prefix}}pech-devel"
      firstname: "Peter"
      lastname: "Christiansen"
      mobile: "+4520815945"
      email: "pech@kb.dk"

    - username: "{{user_prefix}}csr-devel"
      firstname: "Colin"
      lastname: "Samuel Rosenthal"
      mobile: "+4551671287"
      email: "csr@kb.dk"
      # If uid or gid is not specified, use group gid + position in this list.




queue_mapping: "g:{{users_group.name}}:{{users_group.name}}-devel_interactive"


yarn_queue:
  name: "{{users_group.name}}-devel"
  admins: " {{users_group.name}}"
  submitters: " {{users_group.name}}"
  capacity: 40
  max_capacity: 100
  minimum_user_limit: 25
  user_limit: 100
  ordering: priority-utilization
  priority: 1
  state: RUNNING

  children:
    - name: "{{users_group.name}}-devel_batch"
      admins: " {{users_group.name}}"
      submitters: " {{users_group.name}}"
      capacity: 30
      max_capacity: 100
      minimum_user_limit: 25
      user_limit: 100
      ordering: fifo
      priority: 1
      state: RUNNING

    - name: "{{users_group.name}}-devel_interactive"
      admins: " {{users_group.name}}"
      submitters: " {{users_group.name}}"
      capacity: 70
      max_capacity: 80
      minimum_user_limit: 25
      user_limit: 100
      ordering: fair
      priority: 2
      size_based: true
      state: RUNNING