
# Vars in here will be available as p001.*

#project_ipa controls project group and users.
project_ipa:
  name: "devel"
  gid: 20200
  # Project_host is used to set up HBAC rules
  project_host: "narchive-t-admn02.kb.dk"
  users:
    - username: "csr"
      firstname: "Colin"
      lastname: "Rosenthal"
      mobile: "+450000000"
      email: "csr@kb.dk"
      # If uid or gid is not specified, use group gid + position in this list.


queue_mapping: "g:devel:devel_interactive"


yarn_queue:
  name: "devel"
  admins: " devel"
  submitters: " devel"
  capacity: 80
  max_capacity: 100
  minimum_user_limit: 25
  user_limit: 100
  ordering: priority-utilization
  priority: 1
  state: RUNNING

  children:
    - name: "devel_batch"
      admins: " devel"
      submitters: " devel"
      capacity: 30
      max_capacity: 100
      minimum_user_limit: 25
      user_limit: 100
      ordering: fifo
      priority: 1
      state: RUNNING

    - name: "devel_interactive"
      admins: " devel"
      submitters: " devel"
      capacity: 70
      max_capacity: 80
      minimum_user_limit: 25
      user_limit: 100
      ordering: fair
      priority: 2
      size_based: true
      state: RUNNING