---


#Agents should use the proxy
zabbix_agent_server: "{{ (groups['hostgroup_zabbix_proxies'] | map('extract',hostvars, 'ansible_default_ipv4') | first).address }}"

#Comment in to enable active checks.
zabbix_agent_serveractive: "{{ zabbix_agent_server }}"

#This ensures that the hosts are added to zabbix as "managed by proxy"
#Must be same name as the proxy in zabbix, set by zabbix_proxy_name
zabbix_proxy: "{{ (groups['hostgroup_zabbix_proxies'] | map('extract',hostvars, 'ansible_fqdn') | first) }}"

zabbix_agent_tlspskidentity: "{{ zabbix_proxy_tlspskidentity }}"
zabbix_agent_tlspsk_secret: "{{ zabbix_proxy_tlspsk_secret }}"

default_zabbix_host_groups__to_merge:
  - "narchive-prod"

