---
- name: Stop namenode process
  systemd:
    state: stopped
    daemon_reload: yes
    name: hdfs_namenode

- name: Format namenode
  become: yes
  become_user: hdfs
  shell:
    cmd:
      /usr/local/bin/hadoop-invoker.sh hdfs namenode --format > "{{ hadoop_dfs_name }}/formatted"
    executable: /bin/bash
    creates: "{{ hadoop_dfs_name }}/formatted"
  when: primary|bool


- name: Initialize shared edit
  become: yes
  become_user: hdfs
  shell:
    cmd:
      /usr/local/bin/hadoop-invoker.sh hdfs namenode -initializeSharedEdits > "{{ hadoop_dfs_name }}/shared_edits_initialized"
    executable: /bin/bash
    creates: "{{ hadoop_dfs_name }}/shared_edits_initialized"
  when: primary|bool


- name: Bootstrap HA
  become: yes
  become_user: hdfs
  shell:
    cmd:
      /usr/local/bin/hadoop-invoker.sh hdfs namenode -bootstrapStandby > "{{ hadoop_dfs_name }}/bootstrapped"
    executable: /bin/bash
    creates: "{{ hadoop_dfs_name }}/bootstrapped"
  when: not (primary | bool)

- name: Format zkfc
  become: yes
  become_user: hdfs
  shell:
    cmd:
      /usr/local/bin/hadoop-invoker.sh hdfs zkfc -formatZK > "{{ hadoop_dfs_name }}/zkFormatted"
    executable: /bin/bash
    creates: "{{ hadoop_dfs_name }}/zkFormatted"
  when: primary|bool


- name: Start namenode process
  systemd:
    state: restarted
    daemon_reload: yes
    name: hdfs_namenode

- name: Start namenode zkfc process
  systemd:
    state: restarted
    daemon_reload: yes
    name: hdfs_zkfc

