capacity_queues: []

#TODO ensure defaults is last queue here
queue_mappings: "{{lookup('vars', *(projects | map(attribute='name'))) | map(attribute='queue_mapping')  | list }}"



#Each level must sum capacity to 100
yarn_queues:
  - name: root
    admins: "{{yarn_user.name}}"
    submitters: "{{yarn_user.name}}"
    capacity: 100
    ordering: priority-utilization
    max_capacity: 100
    children: "{{lookup('vars', *(projects | map(attribute='name'))) | map(attribute='yarn_queue') | list }}"

