---
# https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipaclient/README.md#base-variables

ipa_server: "{{ groups['ipaserver'] | first }}"

ipa_admin_user: admin
ipa_admin_group: admins

ipaserver_autohome_dir: /sto-data/home
ipaserver_syshome_dir: /sto-data/syshome

ipaclient_autohome_dir: /autohome
ipaclient_syshome_dir: /syshome
#Nessesary to set up the automount
ipaautomount_location: "default"

#Users and groups
hadoop_group: "hadoop"
uid_hadoopGroup: 11000

users_group: "yakusers"
uid_usersGroup: 20000

systemservices_group: "systemservices"
uid_systemserviceGroup: 15000

subadmins_group: "subadmins"
uid_subadminsGroup: 12000


hdfs_user:
  user: "hdfs"
  group: "hdfs"
  uid: 11200
  gid: 11200
  private_group: yes
  extra_groups: [ "{{hadoop_group}}" ]

yarn_user:
  user: "yarn"
  group: "{{hadoop_group}}"
  uid: "{{uid_hadoopGroup|int+2}}"
  gid: "{{uid_hadoopGroup}}"
  private_group: no
  extra_groups: ["{{hadoop_group}}"]

mapreduce_user:
  user: "mapred"
  group: "{{hadoop_group}}"
  uid: "{{uid_hadoopGroup|int+1}}"
  gid: "{{uid_hadoopGroup}}"
  private_group: no
  extra_groups: ["{{hadoop_group}}"]

zookeeper_user:
  user: "zookeeper"
  group: "{{hadoop_group}}"
  uid: "{{uid_hadoopGroup|int+3}}"
  gid: "{{uid_hadoopGroup}}"
  private_group: no
  extra_groups: ["{{hadoop_group}}"]

spark_user:
  user: "spark"
  group: "{{hadoop_group}}"
  uid: "{{uid_hadoopGroup|int+4}}"
  gid: "{{uid_hadoopGroup}}"
  private_group: no
  extra_groups: ["{{hadoop_group}}"]

hive_user:
  user: "hive"
  group: "{{hadoop_group}}"
  uid: "{{uid_hadoopGroup|int+5}}"
  gid: "{{uid_hadoopGroup}}"
  private_group: no
  extra_groups: ["{{hadoop_group}}"]

rstudio_user:
  user: "rstudio-server"
  group: "rstudio-server"
  uid: "{{uid_systemserviceGroup|int+4}}"
  gid: "{{uid_systemserviceGroup|int+4}}"
  private_group: yes
  extra_groups: ["{{systemservices_group}}"]

jupyterhub_user:
  user: "jupyterhub"
  group: "jupyterhub"
  uid: "{{uid_systemserviceGroup|int+5}}"
  gid: "{{uid_systemserviceGroup|int+5}}"
  private_group: yes
  extra_groups: ["{{systemservices_group}}"]

system_users:
  - "{{hdfs_user}}"
  - "{{yarn_user}}"
  - "{{mapreduce_user}}"
  - "{{zookeeper_user}}"
  - "{{spark_user}}"
  - "{{hive_user}}"
  - "{{rstudio_user}}"
  - "{{jupyterhub_user}}"


default_user_groups__to_merge:
  - name: "{{ users_group }}"
    gid: "{{ uid_usersGroup }}"
    description: Standard user accounts, for unprivileged users.
