
#project_ipa controls project group and users.
project_ipa:
  name: "p001"
  gid: 20100
  # Project_host is used to set up HBAC rules
  project_host: "proj001.yak2.net"
  users:
    - username: "userp001"
      firstname: "p001"
      lastname: "User2"
      mobile: "+450000000"
      email: "userp001@{{ipa_domain}}"
      # If uid or gid is not specified, use group gid + position in this list.


queue_mapping: "g:p001:p001_interactive"


yarn_queue:
  name: "p001"
  admins: " p001"
  submitters: " p001"
  capacity: 40
  max_capacity: 100
  minimum_user_limit: 25
  user_limit: 100
  ordering: priority-utilization
  priority: 1
  state: RUNNING

  children:
    - name: "p001_batch"
      admins: " p001"
      submitters: " p001"
      capacity: 30
      max_capacity: 100
      minimum_user_limit: 25
      user_limit: 100
      ordering: fifo
      priority: 1
      state: RUNNING

    - name: "p001_interactive"
      admins: " p001"
      submitters: " p001"
      capacity: 70
      max_capacity: 80
      minimum_user_limit: 25
      user_limit: 100
      ordering: fair
      priority: 2
      size_based: true
      state: RUNNING