---

#Add the NFS service principal for the server and client to Kerberos.
- name: FreeIPA automount setup service
  ipaservice:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "nfs/{{ inventory_hostname }}"
    state: present
    force: yes


#https://blog.delouw.ch/2015/03/14/using-ipa-to-provide-automount-maps-for-nfsv4-home-directories/

#This require the ipa admintools to be installed and the host to be an ipa client
- block:

    - name: setup autohome
      shell: |
        LC_ALL="C.UTF-8"

        #Add the auto.home map
        ipa automountmap-show {{ipaautomount_location}} --map=auto.home || \
          ipa automountmap-add {{ipaautomount_location}} auto.home;

        #And add the auto.home map to auto.master
        ipa automountkey-show {{ipaautomount_location}} auto.master --key "{{ ipaclient_autohome_dir }}" || \
          ipa automountkey-add {{ipaautomount_location}} --key "{{ ipaclient_autohome_dir }}" --info auto.home auto.master;

        #Finally add the key to the auto.home map

        ipa automountkey-show {{ipaautomount_location}}  \
                              --key "*" \
                              --info "-fstype=nfs4,rw,sec=krb5,intr,hard {{ inventory_hostname }}:{{ ipaclient_autohome_dir }}/&" \
                              auto.home || \
          ipa automountkey-add {{ipaautomount_location}} \
            --key "*" \
            --info "-fstype=nfs4,rw,sec=krb5,intr,hard {{ inventory_hostname }}:{{ ipaclient_autohome_dir }}/&" \
            auto.home;


    - name: Tell your NFS service to use NFSv4
      lineinfile:
        path: /etc/sysconfig/nfs
        state: present
        create: yes
        line: 'SECURE_NFS="yes"'

    - name: setup autohome
      shell: ipa-getkeytab --server {{ inventory_hostname }} -p "nfs/{{ inventory_hostname }}" -k /etc/krb5.keytab


    - name: Autohome dir
      file:
        path: "{{ ipaserver_autohome_dir }}"
        owner: root
        group: root
        mode: '0755'
        state: directory

    - name: #Create your NFS share and start the NFS server
      lineinfile:
        path: /etc/exports
        state: present
        create: yes
        line: "{{ ipaserver_autohome_dir }}    {{  autohome_nfs_export_iprange }}(rw,sec=sys:krb5:krb5i:krb5p)"

    - name: admin home
      file:
        path: "{{ ipaserver_autohome_dir }}/{{ipa_admin_user}}"
        owner: "{{ipa_admin_user}}"
        group: "{{ipa_admin_group}}"
        mode: '0700'
        state: directory


    - name: NFS autohome server
      systemd:
        name: nfs-server
        state: restarted
        enabled: yes
        daemon_reload: yes


