---
#TODO merge this into one block
- name: hadoop group
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: hadoop
    gid: "{{users_hadoopGroup}}"
    description: Hadoop System Services

- name: systemservices group
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: systemservices
    gid: "{{users_systemServiceGroup}}"
    description: Standard user accounts, for non-hadoop services

- name: subadmins group
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: subadmins
    gid: "{{users_subadminsGroup}}"
    description: For daily administration of users and hosts

- name: admins group
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: admins
    gid: "{{users_adminsGroup}}"
    description: Account administrators group

- name: subadmins group
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: subadmins
    gid: "{{users_subadminsGroup}}"
    description: For daily administration of users and hosts

- name: nahusers group
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: nahusers
    gid: "{{users_usersGroup}}"
    description: Standard user accounts, for unprivileged users.

- name: hdfs group
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: hdfs
    gid: "{{users_hdfsGroup}}"
    description: HDFS group

- name: p000 group
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: p000
    gid: "{{users_p000Group}}"
    description: Group for project p000
