---

- name: Create user groups
  loop: "{{user_groups}}"
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    description: "{{item.description}}"

