---


- name: system users
  loop: "{{system_users}}"
  ipauser:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{item.user}}"
    first: "{{item.user}}"
    last: "System User"
    userclass: SystemUser

    uid: "{{item.uid | default(omit)}}"
    gid: "{{item.gid | default(omit)}}"
    homedir: "{{ipaclient_syshome_dir}}/{{item.user}}"
    shell: "{{item.shell | default('/bin/bash')}}"
    noprivate: "{{ not item.private_group | default('yes')}}"


- name: "Add system users to system groups "
  loop: "{{system_users}}"
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{ item.extra_groups }}"
    action: member
    user: "{{item.user}}"



