---
- name: system users
  ipauser:
    ipaadmin_password: "{{ipaadmin_password}}"


    users:
      - name: "{{ hdfs_user }}"
        first: Hdfs
        uid: "{{uid_hdfsGroup}}"
        gid: "{{uid_hdfsGroup}}"
        homedir: "{{ ipaclient_syshome_dir }}/{{ hdfs_user }}"

        last: Apache
        userclass: SystemUser
        noprivate: yes
        shell: /bin/bash #Perhaps change this to /sbin/nologin later on

      - name: "{{ mapreduce_user }}"
        first: MapReduce
        uid: "{{uid_hadoopGroup | int + 1}}"
        gid: "{{uid_hadoopGroup}}"
        homedir: "{{ ipaclient_syshome_dir }}/{{ mapreduce_user }}"

        last: Apache
        userclass: SystemUser
        noprivate: yes
        shell: /bin/bash #Perhaps change this to /sbin/nologin later on

      - name: "{{ yarn_user }}"
        first: Yarn
        uid: "{{uid_hadoopGroup | int + 2}}"
        gid: "{{uid_hadoopGroup}}"
        homedir: "{{ ipaclient_syshome_dir }}/{{ yarn_user }}"

        last: Apache
        userclass: SystemUser
        noprivate: yes
        shell: /bin/bash #Perhaps change this to /sbin/nologin later on

      - name: "{{ zookeeper_user }}"
        first: ZooKeeper
        uid: "{{uid_hadoopGroup| int + 3}}"
        gid: "{{uid_hadoopGroup}}"
        homedir: "{{ ipaclient_syshome_dir }}/{{ zookeeper_user }}"

        last: Apache
        userclass: SystemUser
        noprivate: yes
        shell: /sbin/nologin

      - name: "{{ spark_user }}"
        first: Spark2
        uid: "{{uid_hadoopGroup| int + 4}}"
        gid: "{{uid_hadoopGroup}}"
        homedir: "{{ ipaclient_syshome_dir }}/{{ spark_user }}"

        last: Apache
        userclass: SystemUser
        noprivate: yes
        shell: /sbin/nologin

- name: system user groups
  ipagroup:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "{{ hadoop_group }}"
    action: member
    user:
      - "{{ hdfs_user }}"
      - "{{ mapreduce_user }}"
      - "{{ yarn_user }}"
      - "{{ zookeeper_user }}"
      - "{{ spark_user }}"


