---

- name: Install X2Go server
  ansible.builtin.package:
    state: present
    name:
      - x2goserver
      - x2goserver-xsession
      - x2goserver-desktopsharing


- name: Install X2Go desktop for RedHat 7+
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
  ansible.builtin.package:
    state: present
    name:
      - "@Xfce"

- name: Install X2Go desktop for RedHat 7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  ansible.builtin.package:
    state: present
    name:
      - mate-desktop
      - mate-terminal
      - mate-settings-daemon
      - mate-themes #Desktop environment
      - caja # nautilus
      - pluma #gedit
      - atril #evince
      - engrampa #archivemanager
      - firefox #browser

