---


- name: Install EPEL repositories
  ansible.builtin.package:
    state: present
    name:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm"

- name: "on RHEL {{ansible_distribution_major_version}} it is required to also enable the codeready-builder-for-rhel-{{ansible_distribution_major_version}}-*-rpms repository since EPEL packages may depend on packages from it"
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8
  community.general.rhsm_repository:
    name: "codeready-builder-for-rhel-{{ansible_distribution_major_version}}-{{ansible_architecture}}-rpms"



- name: "Install MATE repo for Centos 8"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8
  yum_repository:
    name: "copr:copr.fedorainfracloud.org:stenstorp:MATE"
    description: Copr repo for MATE owned by stenstorp
    baseurl: https://download.copr.fedorainfracloud.org/results/stenstorp/MATE/epel-8-$basearch/
    skip_if_unavailable: True
    gpgcheck: 1
    gpgkey: https://download.copr.fedorainfracloud.org/results/stenstorp/MATE/pubkey.gpg
    repo_gpgcheck: 0
    enabled: yes


- name: Install X2Go
  ansible.builtin.package:
    state: present
    name:
      - x2goserver
      - mate-desktop
      - mate-terminal
      - mate-settings-daemon
      - mate-themes #Desktop environment
      - caja # nautilus
      - pluma #gedit
      - atril #evince
      - engrampa #archivemanager
      - firefox #browser

