---


- name: "Install MATE repo for Centos 8"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8
  yum_repository:
    name: "copr:copr.fedorainfracloud.org:stenstorp:MATE"
    description: Copr repo for MATE owned by stenstorp
    baseurl: https://download.copr.fedorainfracloud.org/results/stenstorp/MATE/epel-8-$basearch/
    skip_if_unavailable: True
    gpgcheck: 1
    gpgkey: https://download.copr.fedorainfracloud.org/results/stenstorp/MATE/pubkey.gpg
    repo_gpgcheck: 0
    enabled: yes


- name: Install X2Go
  ansible.builtin.package:
    state: present
    name:
      - x2goserver
      - mate-desktop
      - mate-terminal
      - mate-settings-daemon
      - mate-themes #Desktop environment
      - caja # nautilus
      - pluma #gedit
      - atril #evince
      - engrampa #archivemanager
      - firefox #browser

