---
- name: handle queue
  include: leafNodes.yml leaf={{queue}} leafName={{queueName}} subqueues={{queue.children | default([]) | map(attribute="name") | join(',')}}

- name: subqueues
  include: parseQueue2.yml queue2={{subqueue}} queueName2={{queueName}}.{{subqueue.name}}
  loop: "{{queue.children }}"
  when: queue.children is defined
  loop_control:
    loop_var: subqueue
