---
- name: create {{ipaclient_autohome_dir}}
  file:
      path: "{{ipaclient_autohome_dir}}"
      state: directory
      mode: '0755'

- name: create {{ipaclient_syshome_dir}}
  file:
        path: "{{ipaclient_syshome_dir}}"
        state: directory
        mode: '0755'

- name: "Mount {{ipaclient_syshome_dir}}"
  mount:
        path: "{{ipaclient_syshome_dir}}"
        src: "{{ipa_server}}:{{ipaserver_syshome_dir}}"
        fstype: "nfs4"
        opts: "rw,defaults,_netdev,hard,intr,_netdev"
        state: mounted

- name: ensure ipa is reloaded
  shell: sss_cache -E

- name: set correct ccache
  replace:
    path: /etc/krb5.conf
    regexp: 'default_ccache_name.*'
    replace: 'default_ccache_name = /tmp/krb5cc_%{uid}'

- name: set correct ccache 2
  replace:
    path: /etc/krb5.conf.d/kcm_default_ccache
    regexp: '^( *default_ccache_name *= *KCM: *)'
    replace: '#\1'

- name: stop sssd KCM service
  systemd:
    state: stopped
    service: sssd-kcm.service
    enabled: no

- name: stop sssd KCM socket service
  systemd:
    state: stopped
    service: sssd-kcm.socket
    enabled: no

- name: restart sssd service
  systemd:
    state: restarted
    service: sssd.service
    enabled: yes


- name: Copy Kerberos profile files
  template:
    src: "{{ item }}"
    dest: "/etc/profile.d/"
    mode: 0644
    owner: "root"
    group: "root"
  with_fileglob:
    - "templates/*"