---

- name: Create Timeline dir
  ansible.builtin.file:
    path: "{{ yarn_timeline_store }}"
    state: directory
    owner: "{{ yarn_user.name }}"
    group: "{{ yarn_user.group }}"

- name: (Re)Start YARN Timeline Server systemd service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: yarn_timeline_server
    enabled: true
