---

- name: Create Timeline dir
  file:
    path: "{{ yarn_timeline_store }}"
    state: directory
    owner: "{{ yarn_user.name }}"
    group: "{{ yarn_user.group }}"
    mode: "0750"

- name: (Re)Start YARN Timeline Server systemd service
  systemd:
    state: started
    daemon_reload: yes
    name: yarn_timeline_server
    enabled: true
