---
- name: 1.Check if EPEL repo is already configured.
  ansible.builtin.stat: path={{ epel_repofile_path }}
  register: epel_repofile_result


- name: 2.Import EPEL GPG key.
  ansible.builtin.rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: 3.Install EPEL repo.
  ansible.builtin.package:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
