---
syslog_forwarder: 127.0.0.1
rsyslog_server: "{{ groups['hostgroup_rsyslog_server'] | map('extract',hostvars, 'ansible_fqdn') | first }}"


syslog_facilities:
  standard: local7
  secure: local5
  audit: local6

